// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum ApplePlatform {
  ios,
  macos,
}

enum AppleSourceKind {
  file,
  network,
  content,
}

enum AppleStreamIntent {
  automatic,
  onDemand,
  live,
}

enum AppleMediaFormat {
  automatic,
  hls,
  mp4,
  mov,
  matroska,
  webm,
  mpegTs,
  mpegPs,
  flv,
  avi,
}

enum AppleNetworkPolicyKind {
  platformDefault,
  managed,
}

enum AppleBufferKind {
  automatic,
  lowLatency,
  smoothPlayback,
  bounded,
}

enum AppleDecoderPolicy {
  systemDefault,
  hardwarePreferred,
  hardwareRequired,
}

enum AppleAudioPolicy {
  appManaged,
  pluginManagedMediaPlayback,
}

enum AppleAssessmentOutcome {
  compatible,
  incompatible,
  requiresInspection,
}

enum ApplePlaybackStatus {
  idle,
  loading,
  ready,
  playing,
  paused,
  buffering,
  completed,
  failed,
}

enum AppleEngine {
  unknown,
  avPlayer,
  managedFallback,
}

enum AppleTrackKind {
  audio,
  video,
}

enum ApplePlayerOperation {
  seek,
  seekToLiveEdge,
  playbackSpeed,
  audioTrackSelection,
  videoConstraints,
  volume,
  stop,
}

enum AppleDecoderMode {
  unknown,
  hardware,
  software,
}

enum AppleDecoderEvidence {
  none,
  hardwareOnly,
  hardwareAndSoftware,
}

enum AppleFailureCategory {
  cancelled,
  unsupported,
  source,
  network,
  container,
  decoder,
  render,
  resource,
  /// Maps to public YlFailureCategory.protocol at the Dart/native boundaries.
  protocolFailure,
  platform,
  /// Maps to public YlFailureCategory.internal at the Dart/native boundaries.
  internalFailure,
}

enum AppleFailureScope {
  command,
  session,
  player,
}

class ApplePlayerOptionsMessage {
  ApplePlayerOptionsMessage({
    required this.decoderPolicy,
    required this.audioPolicy,
    required this.positionUpdateIntervalMs,
  });

  AppleDecoderPolicy decoderPolicy;

  AppleAudioPolicy audioPolicy;

  int positionUpdateIntervalMs;

  List<Object?> _toList() {
    return <Object?>[
      decoderPolicy,
      audioPolicy,
      positionUpdateIntervalMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static ApplePlayerOptionsMessage decode(Object result) {
    result as List<Object?>;
    return ApplePlayerOptionsMessage(
      decoderPolicy: result[0]! as AppleDecoderPolicy,
      audioPolicy: result[1]! as AppleAudioPolicy,
      positionUpdateIntervalMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ApplePlayerOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(decoderPolicy, other.decoderPolicy) && _deepEquals(audioPolicy, other.audioPolicy) && _deepEquals(positionUpdateIntervalMs, other.positionUpdateIntervalMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ApplePlayerOptionsMessage(decoderPolicy: $decoderPolicy, audioPolicy: $audioPolicy, positionUpdateIntervalMs: $positionUpdateIntervalMs)';
  }
}

class AppleCreateRequest {
  AppleCreateRequest({
    required this.schemaMajor,
    required this.options,
  });

  int schemaMajor;

  ApplePlayerOptionsMessage options;

  List<Object?> _toList() {
    return <Object?>[
      schemaMajor,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleCreateRequest decode(Object result) {
    result as List<Object?>;
    return AppleCreateRequest(
      schemaMajor: result[0]! as int,
      options: result[1]! as ApplePlayerOptionsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleCreateRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(schemaMajor, other.schemaMajor) && _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleCreateRequest(schemaMajor: $schemaMajor, options: $options)';
  }
}

class AppleCreateReply {
  AppleCreateReply({
    required this.schemaMajor,
    required this.spiMajor,
    required this.channelSuffix,
    required this.textureId,
    required this.platform,
    required this.implementationName,
    required this.implementationVersion,
    required this.capabilities,
    required this.initialState,
  });

  int schemaMajor;

  int spiMajor;

  String channelSuffix;

  int textureId;

  ApplePlatform platform;

  String implementationName;

  String implementationVersion;

  AppleCapabilitiesMessage capabilities;

  AppleStateMessage initialState;

  List<Object?> _toList() {
    return <Object?>[
      schemaMajor,
      spiMajor,
      channelSuffix,
      textureId,
      platform,
      implementationName,
      implementationVersion,
      capabilities,
      initialState,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleCreateReply decode(Object result) {
    result as List<Object?>;
    return AppleCreateReply(
      schemaMajor: result[0]! as int,
      spiMajor: result[1]! as int,
      channelSuffix: result[2]! as String,
      textureId: result[3]! as int,
      platform: result[4]! as ApplePlatform,
      implementationName: result[5]! as String,
      implementationVersion: result[6]! as String,
      capabilities: result[7]! as AppleCapabilitiesMessage,
      initialState: result[8]! as AppleStateMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleCreateReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(schemaMajor, other.schemaMajor) && _deepEquals(spiMajor, other.spiMajor) && _deepEquals(channelSuffix, other.channelSuffix) && _deepEquals(textureId, other.textureId) && _deepEquals(platform, other.platform) && _deepEquals(implementationName, other.implementationName) && _deepEquals(implementationVersion, other.implementationVersion) && _deepEquals(capabilities, other.capabilities) && _deepEquals(initialState, other.initialState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleCreateReply(schemaMajor: $schemaMajor, spiMajor: $spiMajor, channelSuffix: $channelSuffix, textureId: $textureId, platform: $platform, implementationName: $implementationName, implementationVersion: $implementationVersion, capabilities: $capabilities, initialState: $initialState)';
  }
}

class AppleCapabilitiesMessage {
  AppleCapabilitiesMessage({
    required this.deviceProfile,
    required this.availableEngines,
    required this.decoderEvidence,
    this.maxConcurrentVideoDecoders,
    this.maxWidth,
    this.maxHeight,
    required this.hardwareVideoCodecs,
    required this.supportedOperations,
  });

  String deviceProfile;

  List<AppleEngine> availableEngines;

  AppleDecoderEvidence decoderEvidence;

  int? maxConcurrentVideoDecoders;

  int? maxWidth;

  int? maxHeight;

  List<String> hardwareVideoCodecs;

  List<ApplePlayerOperation> supportedOperations;

  List<Object?> _toList() {
    return <Object?>[
      deviceProfile,
      availableEngines,
      decoderEvidence,
      maxConcurrentVideoDecoders,
      maxWidth,
      maxHeight,
      hardwareVideoCodecs,
      supportedOperations,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleCapabilitiesMessage decode(Object result) {
    result as List<Object?>;
    return AppleCapabilitiesMessage(
      deviceProfile: result[0]! as String,
      availableEngines: (result[1]! as List<Object?>).cast<AppleEngine>(),
      decoderEvidence: result[2]! as AppleDecoderEvidence,
      maxConcurrentVideoDecoders: result[3] as int?,
      maxWidth: result[4] as int?,
      maxHeight: result[5] as int?,
      hardwareVideoCodecs: (result[6]! as List<Object?>).cast<String>(),
      supportedOperations: (result[7]! as List<Object?>).cast<ApplePlayerOperation>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleCapabilitiesMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceProfile, other.deviceProfile) && _deepEquals(availableEngines, other.availableEngines) && _deepEquals(decoderEvidence, other.decoderEvidence) && _deepEquals(maxConcurrentVideoDecoders, other.maxConcurrentVideoDecoders) && _deepEquals(maxWidth, other.maxWidth) && _deepEquals(maxHeight, other.maxHeight) && _deepEquals(hardwareVideoCodecs, other.hardwareVideoCodecs) && _deepEquals(supportedOperations, other.supportedOperations);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleCapabilitiesMessage(deviceProfile: $deviceProfile, availableEngines: $availableEngines, decoderEvidence: $decoderEvidence, maxConcurrentVideoDecoders: $maxConcurrentVideoDecoders, maxWidth: $maxWidth, maxHeight: $maxHeight, hardwareVideoCodecs: $hardwareVideoCodecs, supportedOperations: $supportedOperations)';
  }
}

class AppleHttpRequestMessage {
  AppleHttpRequestMessage({
    required this.headers,
    required this.credentials,
  });

  Map<String, String> headers;

  Map<String, String> credentials;

  List<Object?> _toList() {
    return <Object?>[
      headers,
      credentials,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleHttpRequestMessage decode(Object result) {
    result as List<Object?>;
    return AppleHttpRequestMessage(
      headers: (result[0]! as Map<Object?, Object?>).cast<String, String>(),
      credentials: (result[1]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleHttpRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(headers, other.headers) && _deepEquals(credentials, other.credentials);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleHttpRequestMessage(headers: $headers, credentials: $credentials)';
  }
}

class AppleNetworkPolicyMessage {
  AppleNetworkPolicyMessage({
    required this.kind,
    this.connectTimeoutMs,
    this.readTimeoutMs,
    this.maxRetries,
    this.baseRetryDelayMs,
    this.maxRetryDelayMs,
    this.maxRedirects,
  });

  AppleNetworkPolicyKind kind;

  int? connectTimeoutMs;

  int? readTimeoutMs;

  int? maxRetries;

  int? baseRetryDelayMs;

  int? maxRetryDelayMs;

  int? maxRedirects;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      connectTimeoutMs,
      readTimeoutMs,
      maxRetries,
      baseRetryDelayMs,
      maxRetryDelayMs,
      maxRedirects,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleNetworkPolicyMessage decode(Object result) {
    result as List<Object?>;
    return AppleNetworkPolicyMessage(
      kind: result[0]! as AppleNetworkPolicyKind,
      connectTimeoutMs: result[1] as int?,
      readTimeoutMs: result[2] as int?,
      maxRetries: result[3] as int?,
      baseRetryDelayMs: result[4] as int?,
      maxRetryDelayMs: result[5] as int?,
      maxRedirects: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleNetworkPolicyMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(connectTimeoutMs, other.connectTimeoutMs) && _deepEquals(readTimeoutMs, other.readTimeoutMs) && _deepEquals(maxRetries, other.maxRetries) && _deepEquals(baseRetryDelayMs, other.baseRetryDelayMs) && _deepEquals(maxRetryDelayMs, other.maxRetryDelayMs) && _deepEquals(maxRedirects, other.maxRedirects);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleNetworkPolicyMessage(kind: $kind, connectTimeoutMs: $connectTimeoutMs, readTimeoutMs: $readTimeoutMs, maxRetries: $maxRetries, baseRetryDelayMs: $baseRetryDelayMs, maxRetryDelayMs: $maxRetryDelayMs, maxRedirects: $maxRedirects)';
  }
}

class AppleSourceMessage {
  AppleSourceMessage({
    required this.kind,
    required this.locator,
    required this.intent,
    required this.format,
    this.request,
    this.networkPolicy,
  });

  AppleSourceKind kind;

  String locator;

  AppleStreamIntent intent;

  AppleMediaFormat format;

  AppleHttpRequestMessage? request;

  AppleNetworkPolicyMessage? networkPolicy;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      locator,
      intent,
      format,
      request,
      networkPolicy,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleSourceMessage decode(Object result) {
    result as List<Object?>;
    return AppleSourceMessage(
      kind: result[0]! as AppleSourceKind,
      locator: result[1]! as String,
      intent: result[2]! as AppleStreamIntent,
      format: result[3]! as AppleMediaFormat,
      request: result[4] as AppleHttpRequestMessage?,
      networkPolicy: result[5] as AppleNetworkPolicyMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleSourceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(locator, other.locator) && _deepEquals(intent, other.intent) && _deepEquals(format, other.format) && _deepEquals(request, other.request) && _deepEquals(networkPolicy, other.networkPolicy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleSourceMessage(kind: $kind, locator: $locator, intent: $intent, format: $format, request: $request, networkPolicy: $networkPolicy)';
  }
}

class AppleVideoConstraintsMessage {
  AppleVideoConstraintsMessage({
    this.maxWidth,
    this.maxHeight,
    this.maxBitrate,
  });

  int? maxWidth;

  int? maxHeight;

  int? maxBitrate;

  List<Object?> _toList() {
    return <Object?>[
      maxWidth,
      maxHeight,
      maxBitrate,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleVideoConstraintsMessage decode(Object result) {
    result as List<Object?>;
    return AppleVideoConstraintsMessage(
      maxWidth: result[0] as int?,
      maxHeight: result[1] as int?,
      maxBitrate: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleVideoConstraintsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(maxWidth, other.maxWidth) && _deepEquals(maxHeight, other.maxHeight) && _deepEquals(maxBitrate, other.maxBitrate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleVideoConstraintsMessage(maxWidth: $maxWidth, maxHeight: $maxHeight, maxBitrate: $maxBitrate)';
  }
}

class AppleBufferStrategyMessage {
  AppleBufferStrategyMessage({
    required this.kind,
    this.minDurationMs,
    this.maxDurationMs,
    this.maxManagedBytes,
  });

  AppleBufferKind kind;

  int? minDurationMs;

  int? maxDurationMs;

  int? maxManagedBytes;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      minDurationMs,
      maxDurationMs,
      maxManagedBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleBufferStrategyMessage decode(Object result) {
    result as List<Object?>;
    return AppleBufferStrategyMessage(
      kind: result[0]! as AppleBufferKind,
      minDurationMs: result[1] as int?,
      maxDurationMs: result[2] as int?,
      maxManagedBytes: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleBufferStrategyMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(minDurationMs, other.minDurationMs) && _deepEquals(maxDurationMs, other.maxDurationMs) && _deepEquals(maxManagedBytes, other.maxManagedBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleBufferStrategyMessage(kind: $kind, minDurationMs: $minDurationMs, maxDurationMs: $maxDurationMs, maxManagedBytes: $maxManagedBytes)';
  }
}

class AppleLoadOptionsMessage {
  AppleLoadOptionsMessage({
    required this.autoplay,
    this.startPositionMs,
    required this.bufferStrategy,
    required this.videoConstraints,
    this.decoderPolicyOverride,
  });

  bool autoplay;

  int? startPositionMs;

  AppleBufferStrategyMessage bufferStrategy;

  AppleVideoConstraintsMessage videoConstraints;

  AppleDecoderPolicy? decoderPolicyOverride;

  List<Object?> _toList() {
    return <Object?>[
      autoplay,
      startPositionMs,
      bufferStrategy,
      videoConstraints,
      decoderPolicyOverride,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleLoadOptionsMessage decode(Object result) {
    result as List<Object?>;
    return AppleLoadOptionsMessage(
      autoplay: result[0]! as bool,
      startPositionMs: result[1] as int?,
      bufferStrategy: result[2]! as AppleBufferStrategyMessage,
      videoConstraints: result[3]! as AppleVideoConstraintsMessage,
      decoderPolicyOverride: result[4] as AppleDecoderPolicy?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleLoadOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(autoplay, other.autoplay) && _deepEquals(startPositionMs, other.startPositionMs) && _deepEquals(bufferStrategy, other.bufferStrategy) && _deepEquals(videoConstraints, other.videoConstraints) && _deepEquals(decoderPolicyOverride, other.decoderPolicyOverride);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleLoadOptionsMessage(autoplay: $autoplay, startPositionMs: $startPositionMs, bufferStrategy: $bufferStrategy, videoConstraints: $videoConstraints, decoderPolicyOverride: $decoderPolicyOverride)';
  }
}

class AppleAssessRequest {
  AppleAssessRequest({
    required this.source,
    required this.options,
  });

  AppleSourceMessage source;

  AppleLoadOptionsMessage options;

  List<Object?> _toList() {
    return <Object?>[
      source,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleAssessRequest decode(Object result) {
    result as List<Object?>;
    return AppleAssessRequest(
      source: result[0]! as AppleSourceMessage,
      options: result[1]! as AppleLoadOptionsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleAssessRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(source, other.source) && _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleAssessRequest(source: $source, options: $options)';
  }
}

class AppleLoadRequest {
  AppleLoadRequest({
    required this.loadRequestId,
    required this.source,
    required this.options,
  });

  String loadRequestId;

  AppleSourceMessage source;

  AppleLoadOptionsMessage options;

  List<Object?> _toList() {
    return <Object?>[
      loadRequestId,
      source,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleLoadRequest decode(Object result) {
    result as List<Object?>;
    return AppleLoadRequest(
      loadRequestId: result[0]! as String,
      source: result[1]! as AppleSourceMessage,
      options: result[2]! as AppleLoadOptionsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleLoadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(loadRequestId, other.loadRequestId) && _deepEquals(source, other.source) && _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleLoadRequest(loadRequestId: $loadRequestId, source: $source, options: $options)';
  }
}

class AppleAssessmentReply {
  AppleAssessmentReply({
    required this.outcome,
    this.candidateEngine,
    required this.satisfiedRequirements,
    required this.limitations,
    this.rejection,
  });

  AppleAssessmentOutcome outcome;

  AppleEngine? candidateEngine;

  List<String> satisfiedRequirements;

  List<String> limitations;

  AppleFailureMessage? rejection;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
      candidateEngine,
      satisfiedRequirements,
      limitations,
      rejection,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleAssessmentReply decode(Object result) {
    result as List<Object?>;
    return AppleAssessmentReply(
      outcome: result[0]! as AppleAssessmentOutcome,
      candidateEngine: result[1] as AppleEngine?,
      satisfiedRequirements: (result[2]! as List<Object?>).cast<String>(),
      limitations: (result[3]! as List<Object?>).cast<String>(),
      rejection: result[4] as AppleFailureMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleAssessmentReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) && _deepEquals(candidateEngine, other.candidateEngine) && _deepEquals(satisfiedRequirements, other.satisfiedRequirements) && _deepEquals(limitations, other.limitations) && _deepEquals(rejection, other.rejection);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleAssessmentReply(outcome: $outcome, candidateEngine: $candidateEngine, satisfiedRequirements: $satisfiedRequirements, limitations: $limitations, rejection: $rejection)';
  }
}

class AppleLoadReply {
  AppleLoadReply({
    required this.loadRequestId,
    required this.sessionId,
  });

  String loadRequestId;

  String sessionId;

  List<Object?> _toList() {
    return <Object?>[
      loadRequestId,
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleLoadReply decode(Object result) {
    result as List<Object?>;
    return AppleLoadReply(
      loadRequestId: result[0]! as String,
      sessionId: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleLoadReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(loadRequestId, other.loadRequestId) && _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleLoadReply(loadRequestId: $loadRequestId, sessionId: $sessionId)';
  }
}

class AppleSessionCommand {
  AppleSessionCommand({
    required this.sessionId,
  });

  String sessionId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleSessionCommand decode(Object result) {
    result as List<Object?>;
    return AppleSessionCommand(
      sessionId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleSessionCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleSessionCommand(sessionId: $sessionId)';
  }
}

class AppleSeekCommand {
  AppleSeekCommand({
    required this.sessionId,
    required this.positionMs,
  });

  String sessionId;

  int positionMs;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      positionMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleSeekCommand decode(Object result) {
    result as List<Object?>;
    return AppleSeekCommand(
      sessionId: result[0]! as String,
      positionMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleSeekCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(positionMs, other.positionMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleSeekCommand(sessionId: $sessionId, positionMs: $positionMs)';
  }
}

class AppleSpeedCommand {
  AppleSpeedCommand({
    required this.sessionId,
    required this.speed,
  });

  String sessionId;

  double speed;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      speed,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleSpeedCommand decode(Object result) {
    result as List<Object?>;
    return AppleSpeedCommand(
      sessionId: result[0]! as String,
      speed: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleSpeedCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(speed, other.speed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleSpeedCommand(sessionId: $sessionId, speed: $speed)';
  }
}

class AppleTrackCommand {
  AppleTrackCommand({
    required this.sessionId,
    required this.trackId,
  });

  String sessionId;

  String trackId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      trackId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleTrackCommand decode(Object result) {
    result as List<Object?>;
    return AppleTrackCommand(
      sessionId: result[0]! as String,
      trackId: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleTrackCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(trackId, other.trackId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleTrackCommand(sessionId: $sessionId, trackId: $trackId)';
  }
}

class AppleVideoConstraintsCommand {
  AppleVideoConstraintsCommand({
    required this.sessionId,
    required this.constraints,
  });

  String sessionId;

  AppleVideoConstraintsMessage constraints;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      constraints,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleVideoConstraintsCommand decode(Object result) {
    result as List<Object?>;
    return AppleVideoConstraintsCommand(
      sessionId: result[0]! as String,
      constraints: result[1]! as AppleVideoConstraintsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleVideoConstraintsCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(constraints, other.constraints);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleVideoConstraintsCommand(sessionId: $sessionId, constraints: $constraints)';
  }
}

class AppleDvrWindowMessage {
  AppleDvrWindowMessage({
    required this.startMs,
    required this.endMs,
  });

  int startMs;

  int endMs;

  List<Object?> _toList() {
    return <Object?>[
      startMs,
      endMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleDvrWindowMessage decode(Object result) {
    result as List<Object?>;
    return AppleDvrWindowMessage(
      startMs: result[0]! as int,
      endMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleDvrWindowMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(startMs, other.startMs) && _deepEquals(endMs, other.endMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleDvrWindowMessage(startMs: $startMs, endMs: $endMs)';
  }
}

class AppleTimelineMessage {
  AppleTimelineMessage({
    required this.positionMs,
    this.durationMs,
    required this.bufferedPositionMs,
    required this.isSeekable,
    required this.isLive,
    this.isAtLiveEdge,
    this.liveOffsetMs,
    this.dvrWindow,
  });

  int positionMs;

  int? durationMs;

  int bufferedPositionMs;

  bool isSeekable;

  bool isLive;

  bool? isAtLiveEdge;

  int? liveOffsetMs;

  AppleDvrWindowMessage? dvrWindow;

  List<Object?> _toList() {
    return <Object?>[
      positionMs,
      durationMs,
      bufferedPositionMs,
      isSeekable,
      isLive,
      isAtLiveEdge,
      liveOffsetMs,
      dvrWindow,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleTimelineMessage decode(Object result) {
    result as List<Object?>;
    return AppleTimelineMessage(
      positionMs: result[0]! as int,
      durationMs: result[1] as int?,
      bufferedPositionMs: result[2]! as int,
      isSeekable: result[3]! as bool,
      isLive: result[4]! as bool,
      isAtLiveEdge: result[5] as bool?,
      liveOffsetMs: result[6] as int?,
      dvrWindow: result[7] as AppleDvrWindowMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleTimelineMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(positionMs, other.positionMs) && _deepEquals(durationMs, other.durationMs) && _deepEquals(bufferedPositionMs, other.bufferedPositionMs) && _deepEquals(isSeekable, other.isSeekable) && _deepEquals(isLive, other.isLive) && _deepEquals(isAtLiveEdge, other.isAtLiveEdge) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(dvrWindow, other.dvrWindow);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleTimelineMessage(positionMs: $positionMs, durationMs: $durationMs, bufferedPositionMs: $bufferedPositionMs, isSeekable: $isSeekable, isLive: $isLive, isAtLiveEdge: $isAtLiveEdge, liveOffsetMs: $liveOffsetMs, dvrWindow: $dvrWindow)';
  }
}

class AppleSizeMessage {
  AppleSizeMessage({
    required this.width,
    required this.height,
  });

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleSizeMessage decode(Object result) {
    result as List<Object?>;
    return AppleSizeMessage(
      width: result[0]! as double,
      height: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleSizeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleSizeMessage(width: $width, height: $height)';
  }
}

class AppleVideoGeometryMessage {
  AppleVideoGeometryMessage({
    required this.encodedSize,
    required this.displaySize,
    required this.pixelAspectRatio,
    required this.rotationDegrees,
  });

  AppleSizeMessage encodedSize;

  AppleSizeMessage displaySize;

  double pixelAspectRatio;

  int rotationDegrees;

  List<Object?> _toList() {
    return <Object?>[
      encodedSize,
      displaySize,
      pixelAspectRatio,
      rotationDegrees,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleVideoGeometryMessage decode(Object result) {
    result as List<Object?>;
    return AppleVideoGeometryMessage(
      encodedSize: result[0]! as AppleSizeMessage,
      displaySize: result[1]! as AppleSizeMessage,
      pixelAspectRatio: result[2]! as double,
      rotationDegrees: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleVideoGeometryMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encodedSize, other.encodedSize) && _deepEquals(displaySize, other.displaySize) && _deepEquals(pixelAspectRatio, other.pixelAspectRatio) && _deepEquals(rotationDegrees, other.rotationDegrees);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleVideoGeometryMessage(encodedSize: $encodedSize, displaySize: $displaySize, pixelAspectRatio: $pixelAspectRatio, rotationDegrees: $rotationDegrees)';
  }
}

class AppleTrackMessage {
  AppleTrackMessage({
    required this.id,
    required this.kind,
    this.label,
    this.language,
    this.codec,
    this.bitrate,
    this.width,
    this.height,
    required this.isSelected,
  });

  String id;

  AppleTrackKind kind;

  String? label;

  String? language;

  String? codec;

  int? bitrate;

  int? width;

  int? height;

  bool isSelected;

  List<Object?> _toList() {
    return <Object?>[
      id,
      kind,
      label,
      language,
      codec,
      bitrate,
      width,
      height,
      isSelected,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleTrackMessage decode(Object result) {
    result as List<Object?>;
    return AppleTrackMessage(
      id: result[0]! as String,
      kind: result[1]! as AppleTrackKind,
      label: result[2] as String?,
      language: result[3] as String?,
      codec: result[4] as String?,
      bitrate: result[5] as int?,
      width: result[6] as int?,
      height: result[7] as int?,
      isSelected: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleTrackMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(kind, other.kind) && _deepEquals(label, other.label) && _deepEquals(language, other.language) && _deepEquals(codec, other.codec) && _deepEquals(bitrate, other.bitrate) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(isSelected, other.isSelected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleTrackMessage(id: $id, kind: $kind, label: $label, language: $language, codec: $codec, bitrate: $bitrate, width: $width, height: $height, isSelected: $isSelected)';
  }
}

class AppleMetricsMessage {
  AppleMetricsMessage({
    this.loadToReadyMs,
    this.loadToFirstFrameMs,
    this.rebufferCount,
    this.rebufferDurationMs,
    this.droppedVideoFrames,
    this.audioUnderruns,
    this.estimatedBitrate,
    this.managedBufferedDurationMs,
    this.managedBufferedBytes,
    this.liveOffsetMs,
    this.reconnectCount,
  });

  int? loadToReadyMs;

  int? loadToFirstFrameMs;

  int? rebufferCount;

  int? rebufferDurationMs;

  int? droppedVideoFrames;

  int? audioUnderruns;

  int? estimatedBitrate;

  int? managedBufferedDurationMs;

  int? managedBufferedBytes;

  int? liveOffsetMs;

  int? reconnectCount;

  List<Object?> _toList() {
    return <Object?>[
      loadToReadyMs,
      loadToFirstFrameMs,
      rebufferCount,
      rebufferDurationMs,
      droppedVideoFrames,
      audioUnderruns,
      estimatedBitrate,
      managedBufferedDurationMs,
      managedBufferedBytes,
      liveOffsetMs,
      reconnectCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleMetricsMessage decode(Object result) {
    result as List<Object?>;
    return AppleMetricsMessage(
      loadToReadyMs: result[0] as int?,
      loadToFirstFrameMs: result[1] as int?,
      rebufferCount: result[2] as int?,
      rebufferDurationMs: result[3] as int?,
      droppedVideoFrames: result[4] as int?,
      audioUnderruns: result[5] as int?,
      estimatedBitrate: result[6] as int?,
      managedBufferedDurationMs: result[7] as int?,
      managedBufferedBytes: result[8] as int?,
      liveOffsetMs: result[9] as int?,
      reconnectCount: result[10] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleMetricsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(loadToReadyMs, other.loadToReadyMs) && _deepEquals(loadToFirstFrameMs, other.loadToFirstFrameMs) && _deepEquals(rebufferCount, other.rebufferCount) && _deepEquals(rebufferDurationMs, other.rebufferDurationMs) && _deepEquals(droppedVideoFrames, other.droppedVideoFrames) && _deepEquals(audioUnderruns, other.audioUnderruns) && _deepEquals(estimatedBitrate, other.estimatedBitrate) && _deepEquals(managedBufferedDurationMs, other.managedBufferedDurationMs) && _deepEquals(managedBufferedBytes, other.managedBufferedBytes) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(reconnectCount, other.reconnectCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleMetricsMessage(loadToReadyMs: $loadToReadyMs, loadToFirstFrameMs: $loadToFirstFrameMs, rebufferCount: $rebufferCount, rebufferDurationMs: $rebufferDurationMs, droppedVideoFrames: $droppedVideoFrames, audioUnderruns: $audioUnderruns, estimatedBitrate: $estimatedBitrate, managedBufferedDurationMs: $managedBufferedDurationMs, managedBufferedBytes: $managedBufferedBytes, liveOffsetMs: $liveOffsetMs, reconnectCount: $reconnectCount)';
  }
}

class AppleFailureMessage {
  AppleFailureMessage({
    required this.category,
    required this.code,
    required this.message,
    required this.retryable,
    required this.scope,
    required this.diagnosticId,
  });

  AppleFailureCategory category;

  String code;

  String message;

  bool retryable;

  AppleFailureScope scope;

  String diagnosticId;

  List<Object?> _toList() {
    return <Object?>[
      category,
      code,
      message,
      retryable,
      scope,
      diagnosticId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleFailureMessage decode(Object result) {
    result as List<Object?>;
    return AppleFailureMessage(
      category: result[0]! as AppleFailureCategory,
      code: result[1]! as String,
      message: result[2]! as String,
      retryable: result[3]! as bool,
      scope: result[4]! as AppleFailureScope,
      diagnosticId: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleFailureMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(category, other.category) && _deepEquals(code, other.code) && _deepEquals(message, other.message) && _deepEquals(retryable, other.retryable) && _deepEquals(scope, other.scope) && _deepEquals(diagnosticId, other.diagnosticId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleFailureMessage(category: $category, code: $code, message: $message, retryable: $retryable, scope: $scope, diagnosticId: $diagnosticId)';
  }
}

class AppleStateMessage {
  AppleStateMessage({
    this.loadRequestId,
    this.sessionId,
    required this.revision,
    required this.sequence,
    required this.status,
    required this.timeline,
    this.geometry,
    required this.audioTracks,
    required this.videoTracks,
    required this.engine,
    required this.decoderMode,
    this.decoderIdentity,
    required this.metrics,
    this.failure,
  });

  String? loadRequestId;

  String? sessionId;

  int revision;

  int sequence;

  ApplePlaybackStatus status;

  AppleTimelineMessage timeline;

  AppleVideoGeometryMessage? geometry;

  List<AppleTrackMessage> audioTracks;

  List<AppleTrackMessage> videoTracks;

  AppleEngine engine;

  AppleDecoderMode decoderMode;

  String? decoderIdentity;

  AppleMetricsMessage metrics;

  AppleFailureMessage? failure;

  List<Object?> _toList() {
    return <Object?>[
      loadRequestId,
      sessionId,
      revision,
      sequence,
      status,
      timeline,
      geometry,
      audioTracks,
      videoTracks,
      engine,
      decoderMode,
      decoderIdentity,
      metrics,
      failure,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleStateMessage decode(Object result) {
    result as List<Object?>;
    return AppleStateMessage(
      loadRequestId: result[0] as String?,
      sessionId: result[1] as String?,
      revision: result[2]! as int,
      sequence: result[3]! as int,
      status: result[4]! as ApplePlaybackStatus,
      timeline: result[5]! as AppleTimelineMessage,
      geometry: result[6] as AppleVideoGeometryMessage?,
      audioTracks: (result[7]! as List<Object?>).cast<AppleTrackMessage>(),
      videoTracks: (result[8]! as List<Object?>).cast<AppleTrackMessage>(),
      engine: result[9]! as AppleEngine,
      decoderMode: result[10]! as AppleDecoderMode,
      decoderIdentity: result[11] as String?,
      metrics: result[12]! as AppleMetricsMessage,
      failure: result[13] as AppleFailureMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(loadRequestId, other.loadRequestId) && _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(status, other.status) && _deepEquals(timeline, other.timeline) && _deepEquals(geometry, other.geometry) && _deepEquals(audioTracks, other.audioTracks) && _deepEquals(videoTracks, other.videoTracks) && _deepEquals(engine, other.engine) && _deepEquals(decoderMode, other.decoderMode) && _deepEquals(decoderIdentity, other.decoderIdentity) && _deepEquals(metrics, other.metrics) && _deepEquals(failure, other.failure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleStateMessage(loadRequestId: $loadRequestId, sessionId: $sessionId, revision: $revision, sequence: $sequence, status: $status, timeline: $timeline, geometry: $geometry, audioTracks: $audioTracks, videoTracks: $videoTracks, engine: $engine, decoderMode: $decoderMode, decoderIdentity: $decoderIdentity, metrics: $metrics, failure: $failure)';
  }
}

class AppleStateDeltaMessage {
  AppleStateDeltaMessage({
    required this.sessionId,
    required this.previousRevision,
    required this.revision,
    required this.sequence,
    this.positionMs,
    this.bufferedPositionMs,
    required this.hasIsAtLiveEdge,
    this.isAtLiveEdge,
    required this.hasLiveOffsetMs,
    this.liveOffsetMs,
    this.metrics,
  });

  String sessionId;

  int previousRevision;

  int revision;

  int sequence;

  int? positionMs;

  int? bufferedPositionMs;

  bool hasIsAtLiveEdge;

  bool? isAtLiveEdge;

  bool hasLiveOffsetMs;

  int? liveOffsetMs;

  AppleMetricsDeltaMessage? metrics;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      previousRevision,
      revision,
      sequence,
      positionMs,
      bufferedPositionMs,
      hasIsAtLiveEdge,
      isAtLiveEdge,
      hasLiveOffsetMs,
      liveOffsetMs,
      metrics,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleStateDeltaMessage decode(Object result) {
    result as List<Object?>;
    return AppleStateDeltaMessage(
      sessionId: result[0]! as String,
      previousRevision: result[1]! as int,
      revision: result[2]! as int,
      sequence: result[3]! as int,
      positionMs: result[4] as int?,
      bufferedPositionMs: result[5] as int?,
      hasIsAtLiveEdge: result[6]! as bool,
      isAtLiveEdge: result[7] as bool?,
      hasLiveOffsetMs: result[8]! as bool,
      liveOffsetMs: result[9] as int?,
      metrics: result[10] as AppleMetricsDeltaMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleStateDeltaMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(previousRevision, other.previousRevision) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(positionMs, other.positionMs) && _deepEquals(bufferedPositionMs, other.bufferedPositionMs) && _deepEquals(hasIsAtLiveEdge, other.hasIsAtLiveEdge) && _deepEquals(isAtLiveEdge, other.isAtLiveEdge) && _deepEquals(hasLiveOffsetMs, other.hasLiveOffsetMs) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(metrics, other.metrics);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleStateDeltaMessage(sessionId: $sessionId, previousRevision: $previousRevision, revision: $revision, sequence: $sequence, positionMs: $positionMs, bufferedPositionMs: $bufferedPositionMs, hasIsAtLiveEdge: $hasIsAtLiveEdge, isAtLiveEdge: $isAtLiveEdge, hasLiveOffsetMs: $hasLiveOffsetMs, liveOffsetMs: $liveOffsetMs, metrics: $metrics)';
  }
}

class AppleMetricsDeltaMessage {
  AppleMetricsDeltaMessage({
    required this.hasLoadToReadyMs,
    this.loadToReadyMs,
    required this.hasLoadToFirstFrameMs,
    this.loadToFirstFrameMs,
    required this.hasRebufferCount,
    this.rebufferCount,
    required this.hasRebufferDurationMs,
    this.rebufferDurationMs,
    required this.hasDroppedVideoFrames,
    this.droppedVideoFrames,
    required this.hasAudioUnderruns,
    this.audioUnderruns,
    required this.hasEstimatedBitrate,
    this.estimatedBitrate,
    required this.hasManagedBufferedDurationMs,
    this.managedBufferedDurationMs,
    required this.hasManagedBufferedBytes,
    this.managedBufferedBytes,
    required this.hasLiveOffsetMs,
    this.liveOffsetMs,
    required this.hasReconnectCount,
    this.reconnectCount,
  });

  bool hasLoadToReadyMs;

  int? loadToReadyMs;

  bool hasLoadToFirstFrameMs;

  int? loadToFirstFrameMs;

  bool hasRebufferCount;

  int? rebufferCount;

  bool hasRebufferDurationMs;

  int? rebufferDurationMs;

  bool hasDroppedVideoFrames;

  int? droppedVideoFrames;

  bool hasAudioUnderruns;

  int? audioUnderruns;

  bool hasEstimatedBitrate;

  int? estimatedBitrate;

  bool hasManagedBufferedDurationMs;

  int? managedBufferedDurationMs;

  bool hasManagedBufferedBytes;

  int? managedBufferedBytes;

  bool hasLiveOffsetMs;

  int? liveOffsetMs;

  bool hasReconnectCount;

  int? reconnectCount;

  List<Object?> _toList() {
    return <Object?>[
      hasLoadToReadyMs,
      loadToReadyMs,
      hasLoadToFirstFrameMs,
      loadToFirstFrameMs,
      hasRebufferCount,
      rebufferCount,
      hasRebufferDurationMs,
      rebufferDurationMs,
      hasDroppedVideoFrames,
      droppedVideoFrames,
      hasAudioUnderruns,
      audioUnderruns,
      hasEstimatedBitrate,
      estimatedBitrate,
      hasManagedBufferedDurationMs,
      managedBufferedDurationMs,
      hasManagedBufferedBytes,
      managedBufferedBytes,
      hasLiveOffsetMs,
      liveOffsetMs,
      hasReconnectCount,
      reconnectCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleMetricsDeltaMessage decode(Object result) {
    result as List<Object?>;
    return AppleMetricsDeltaMessage(
      hasLoadToReadyMs: result[0]! as bool,
      loadToReadyMs: result[1] as int?,
      hasLoadToFirstFrameMs: result[2]! as bool,
      loadToFirstFrameMs: result[3] as int?,
      hasRebufferCount: result[4]! as bool,
      rebufferCount: result[5] as int?,
      hasRebufferDurationMs: result[6]! as bool,
      rebufferDurationMs: result[7] as int?,
      hasDroppedVideoFrames: result[8]! as bool,
      droppedVideoFrames: result[9] as int?,
      hasAudioUnderruns: result[10]! as bool,
      audioUnderruns: result[11] as int?,
      hasEstimatedBitrate: result[12]! as bool,
      estimatedBitrate: result[13] as int?,
      hasManagedBufferedDurationMs: result[14]! as bool,
      managedBufferedDurationMs: result[15] as int?,
      hasManagedBufferedBytes: result[16]! as bool,
      managedBufferedBytes: result[17] as int?,
      hasLiveOffsetMs: result[18]! as bool,
      liveOffsetMs: result[19] as int?,
      hasReconnectCount: result[20]! as bool,
      reconnectCount: result[21] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleMetricsDeltaMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasLoadToReadyMs, other.hasLoadToReadyMs) && _deepEquals(loadToReadyMs, other.loadToReadyMs) && _deepEquals(hasLoadToFirstFrameMs, other.hasLoadToFirstFrameMs) && _deepEquals(loadToFirstFrameMs, other.loadToFirstFrameMs) && _deepEquals(hasRebufferCount, other.hasRebufferCount) && _deepEquals(rebufferCount, other.rebufferCount) && _deepEquals(hasRebufferDurationMs, other.hasRebufferDurationMs) && _deepEquals(rebufferDurationMs, other.rebufferDurationMs) && _deepEquals(hasDroppedVideoFrames, other.hasDroppedVideoFrames) && _deepEquals(droppedVideoFrames, other.droppedVideoFrames) && _deepEquals(hasAudioUnderruns, other.hasAudioUnderruns) && _deepEquals(audioUnderruns, other.audioUnderruns) && _deepEquals(hasEstimatedBitrate, other.hasEstimatedBitrate) && _deepEquals(estimatedBitrate, other.estimatedBitrate) && _deepEquals(hasManagedBufferedDurationMs, other.hasManagedBufferedDurationMs) && _deepEquals(managedBufferedDurationMs, other.managedBufferedDurationMs) && _deepEquals(hasManagedBufferedBytes, other.hasManagedBufferedBytes) && _deepEquals(managedBufferedBytes, other.managedBufferedBytes) && _deepEquals(hasLiveOffsetMs, other.hasLiveOffsetMs) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(hasReconnectCount, other.hasReconnectCount) && _deepEquals(reconnectCount, other.reconnectCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleMetricsDeltaMessage(hasLoadToReadyMs: $hasLoadToReadyMs, loadToReadyMs: $loadToReadyMs, hasLoadToFirstFrameMs: $hasLoadToFirstFrameMs, loadToFirstFrameMs: $loadToFirstFrameMs, hasRebufferCount: $hasRebufferCount, rebufferCount: $rebufferCount, hasRebufferDurationMs: $hasRebufferDurationMs, rebufferDurationMs: $rebufferDurationMs, hasDroppedVideoFrames: $hasDroppedVideoFrames, droppedVideoFrames: $droppedVideoFrames, hasAudioUnderruns: $hasAudioUnderruns, audioUnderruns: $audioUnderruns, hasEstimatedBitrate: $hasEstimatedBitrate, estimatedBitrate: $estimatedBitrate, hasManagedBufferedDurationMs: $hasManagedBufferedDurationMs, managedBufferedDurationMs: $managedBufferedDurationMs, hasManagedBufferedBytes: $hasManagedBufferedBytes, managedBufferedBytes: $managedBufferedBytes, hasLiveOffsetMs: $hasLiveOffsetMs, liveOffsetMs: $liveOffsetMs, hasReconnectCount: $hasReconnectCount, reconnectCount: $reconnectCount)';
  }
}

class AppleFirstFrameMessage {
  AppleFirstFrameMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleFirstFrameMessage decode(Object result) {
    result as List<Object?>;
    return AppleFirstFrameMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleFirstFrameMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleFirstFrameMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs)';
  }
}

class AppleRetryScheduledMessage {
  AppleRetryScheduledMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
    required this.retryIndex,
    required this.delayMs,
    required this.failure,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  int retryIndex;

  int delayMs;

  AppleFailureMessage failure;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
      retryIndex,
      delayMs,
      failure,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleRetryScheduledMessage decode(Object result) {
    result as List<Object?>;
    return AppleRetryScheduledMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
      retryIndex: result[4]! as int,
      delayMs: result[5]! as int,
      failure: result[6]! as AppleFailureMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleRetryScheduledMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs) && _deepEquals(retryIndex, other.retryIndex) && _deepEquals(delayMs, other.delayMs) && _deepEquals(failure, other.failure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleRetryScheduledMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs, retryIndex: $retryIndex, delayMs: $delayMs, failure: $failure)';
  }
}

class AppleEngineChangedMessage {
  AppleEngineChangedMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
    required this.previousEngine,
    required this.engine,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  AppleEngine previousEngine;

  AppleEngine engine;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
      previousEngine,
      engine,
    ];
  }

  Object encode() {
    return _toList();  }

  static AppleEngineChangedMessage decode(Object result) {
    result as List<Object?>;
    return AppleEngineChangedMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
      previousEngine: result[4]! as AppleEngine,
      engine: result[5]! as AppleEngine,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AppleEngineChangedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs) && _deepEquals(previousEngine, other.previousEngine) && _deepEquals(engine, other.engine);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AppleEngineChangedMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs, previousEngine: $previousEngine, engine: $engine)';
  }
}

class ApplePlaybackFailedMessage {
  ApplePlaybackFailedMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
    required this.failure,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  AppleFailureMessage failure;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
      failure,
    ];
  }

  Object encode() {
    return _toList();  }

  static ApplePlaybackFailedMessage decode(Object result) {
    result as List<Object?>;
    return ApplePlaybackFailedMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
      failure: result[4]! as AppleFailureMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ApplePlaybackFailedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs) && _deepEquals(failure, other.failure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ApplePlaybackFailedMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs, failure: $failure)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ApplePlatform) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AppleSourceKind) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AppleStreamIntent) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is AppleMediaFormat) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is AppleNetworkPolicyKind) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is AppleBufferKind) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is AppleDecoderPolicy) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is AppleAudioPolicy) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is AppleAssessmentOutcome) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is ApplePlaybackStatus) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is AppleEngine) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is AppleTrackKind) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    }    else if (value is ApplePlayerOperation) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    }    else if (value is AppleDecoderMode) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    }    else if (value is AppleDecoderEvidence) {
      buffer.putUint8(143);
      writeValue(buffer, value.index);
    }    else if (value is AppleFailureCategory) {
      buffer.putUint8(144);
      writeValue(buffer, value.index);
    }    else if (value is AppleFailureScope) {
      buffer.putUint8(145);
      writeValue(buffer, value.index);
    }    else if (value is ApplePlayerOptionsMessage) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is AppleCreateRequest) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is AppleCreateReply) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is AppleCapabilitiesMessage) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is AppleHttpRequestMessage) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is AppleNetworkPolicyMessage) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is AppleSourceMessage) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is AppleVideoConstraintsMessage) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is AppleBufferStrategyMessage) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    }    else if (value is AppleLoadOptionsMessage) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    }    else if (value is AppleAssessRequest) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    }    else if (value is AppleLoadRequest) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    }    else if (value is AppleAssessmentReply) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    }    else if (value is AppleLoadReply) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    }    else if (value is AppleSessionCommand) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    }    else if (value is AppleSeekCommand) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    }    else if (value is AppleSpeedCommand) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    }    else if (value is AppleTrackCommand) {
      buffer.putUint8(163);
      writeValue(buffer, value.encode());
    }    else if (value is AppleVideoConstraintsCommand) {
      buffer.putUint8(164);
      writeValue(buffer, value.encode());
    }    else if (value is AppleDvrWindowMessage) {
      buffer.putUint8(165);
      writeValue(buffer, value.encode());
    }    else if (value is AppleTimelineMessage) {
      buffer.putUint8(166);
      writeValue(buffer, value.encode());
    }    else if (value is AppleSizeMessage) {
      buffer.putUint8(167);
      writeValue(buffer, value.encode());
    }    else if (value is AppleVideoGeometryMessage) {
      buffer.putUint8(168);
      writeValue(buffer, value.encode());
    }    else if (value is AppleTrackMessage) {
      buffer.putUint8(169);
      writeValue(buffer, value.encode());
    }    else if (value is AppleMetricsMessage) {
      buffer.putUint8(170);
      writeValue(buffer, value.encode());
    }    else if (value is AppleFailureMessage) {
      buffer.putUint8(171);
      writeValue(buffer, value.encode());
    }    else if (value is AppleStateMessage) {
      buffer.putUint8(172);
      writeValue(buffer, value.encode());
    }    else if (value is AppleStateDeltaMessage) {
      buffer.putUint8(173);
      writeValue(buffer, value.encode());
    }    else if (value is AppleMetricsDeltaMessage) {
      buffer.putUint8(174);
      writeValue(buffer, value.encode());
    }    else if (value is AppleFirstFrameMessage) {
      buffer.putUint8(175);
      writeValue(buffer, value.encode());
    }    else if (value is AppleRetryScheduledMessage) {
      buffer.putUint8(176);
      writeValue(buffer, value.encode());
    }    else if (value is AppleEngineChangedMessage) {
      buffer.putUint8(177);
      writeValue(buffer, value.encode());
    }    else if (value is ApplePlaybackFailedMessage) {
      buffer.putUint8(178);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ApplePlatform.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleSourceKind.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleStreamIntent.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleMediaFormat.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleNetworkPolicyKind.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleBufferKind.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleDecoderPolicy.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleAudioPolicy.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleAssessmentOutcome.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : ApplePlaybackStatus.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleEngine.values[value];
      case 140:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleTrackKind.values[value];
      case 141:
        final value = readValue(buffer) as int?;
        return value == null ? null : ApplePlayerOperation.values[value];
      case 142:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleDecoderMode.values[value];
      case 143:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleDecoderEvidence.values[value];
      case 144:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleFailureCategory.values[value];
      case 145:
        final value = readValue(buffer) as int?;
        return value == null ? null : AppleFailureScope.values[value];
      case 146:
        return ApplePlayerOptionsMessage.decode(readValue(buffer)!);
      case 147:
        return AppleCreateRequest.decode(readValue(buffer)!);
      case 148:
        return AppleCreateReply.decode(readValue(buffer)!);
      case 149:
        return AppleCapabilitiesMessage.decode(readValue(buffer)!);
      case 150:
        return AppleHttpRequestMessage.decode(readValue(buffer)!);
      case 151:
        return AppleNetworkPolicyMessage.decode(readValue(buffer)!);
      case 152:
        return AppleSourceMessage.decode(readValue(buffer)!);
      case 153:
        return AppleVideoConstraintsMessage.decode(readValue(buffer)!);
      case 154:
        return AppleBufferStrategyMessage.decode(readValue(buffer)!);
      case 155:
        return AppleLoadOptionsMessage.decode(readValue(buffer)!);
      case 156:
        return AppleAssessRequest.decode(readValue(buffer)!);
      case 157:
        return AppleLoadRequest.decode(readValue(buffer)!);
      case 158:
        return AppleAssessmentReply.decode(readValue(buffer)!);
      case 159:
        return AppleLoadReply.decode(readValue(buffer)!);
      case 160:
        return AppleSessionCommand.decode(readValue(buffer)!);
      case 161:
        return AppleSeekCommand.decode(readValue(buffer)!);
      case 162:
        return AppleSpeedCommand.decode(readValue(buffer)!);
      case 163:
        return AppleTrackCommand.decode(readValue(buffer)!);
      case 164:
        return AppleVideoConstraintsCommand.decode(readValue(buffer)!);
      case 165:
        return AppleDvrWindowMessage.decode(readValue(buffer)!);
      case 166:
        return AppleTimelineMessage.decode(readValue(buffer)!);
      case 167:
        return AppleSizeMessage.decode(readValue(buffer)!);
      case 168:
        return AppleVideoGeometryMessage.decode(readValue(buffer)!);
      case 169:
        return AppleTrackMessage.decode(readValue(buffer)!);
      case 170:
        return AppleMetricsMessage.decode(readValue(buffer)!);
      case 171:
        return AppleFailureMessage.decode(readValue(buffer)!);
      case 172:
        return AppleStateMessage.decode(readValue(buffer)!);
      case 173:
        return AppleStateDeltaMessage.decode(readValue(buffer)!);
      case 174:
        return AppleMetricsDeltaMessage.decode(readValue(buffer)!);
      case 175:
        return AppleFirstFrameMessage.decode(readValue(buffer)!);
      case 176:
        return AppleRetryScheduledMessage.decode(readValue(buffer)!);
      case 177:
        return AppleEngineChangedMessage.decode(readValue(buffer)!);
      case 178:
        return ApplePlaybackFailedMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ApplePlayerFactoryHostApi {
  /// Constructor for [ApplePlayerFactoryHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ApplePlayerFactoryHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AppleCreateReply> create(AppleCreateRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerFactoryHostApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AppleCreateReply;
  }
}

class ApplePlayerHostApi {
  /// Constructor for [ApplePlayerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ApplePlayerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> attach() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.attach$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AppleAssessmentReply> assess(AppleAssessRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.assess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AppleAssessmentReply;
  }

  Future<AppleLoadReply> load(AppleLoadRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AppleLoadReply;
  }

  Future<void> play(AppleSessionCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pause(AppleSessionCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekTo(AppleSeekCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.seekTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekToLiveEdge(AppleSessionCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.seekToLiveEdge$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setPlaybackSpeed(AppleSpeedCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.setPlaybackSpeed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> selectAudioTrack(AppleTrackCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.selectAudioTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVideoConstraints(AppleVideoConstraintsCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.setVideoConstraints$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVolume(double volume) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[volume]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_apple.ApplePlayerHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class ApplePlayerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onState(AppleStateMessage state);

  void onStateDelta(AppleStateDeltaMessage delta);

  void onFirstFrame(AppleFirstFrameMessage event);

  void onRetryScheduled(AppleRetryScheduledMessage event);

  void onEngineChanged(AppleEngineChangedMessage event);

  void onPlaybackFailed(ApplePlaybackFailedMessage event);

  static void setUp(ApplePlayerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_apple.ApplePlayerFlutterApi.onState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppleStateMessage arg_state = args[0]! as AppleStateMessage;
          try {
            api.onState(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_apple.ApplePlayerFlutterApi.onStateDelta$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppleStateDeltaMessage arg_delta = args[0]! as AppleStateDeltaMessage;
          try {
            api.onStateDelta(arg_delta);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_apple.ApplePlayerFlutterApi.onFirstFrame$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppleFirstFrameMessage arg_event = args[0]! as AppleFirstFrameMessage;
          try {
            api.onFirstFrame(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_apple.ApplePlayerFlutterApi.onRetryScheduled$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppleRetryScheduledMessage arg_event = args[0]! as AppleRetryScheduledMessage;
          try {
            api.onRetryScheduled(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_apple.ApplePlayerFlutterApi.onEngineChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AppleEngineChangedMessage arg_event = args[0]! as AppleEngineChangedMessage;
          try {
            api.onEngineChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_apple.ApplePlayerFlutterApi.onPlaybackFailed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ApplePlaybackFailedMessage arg_event = args[0]! as ApplePlaybackFailedMessage;
          try {
            api.onPlaybackFailed(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
