// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum AndroidSourceKind {
  file,
  network,
  content,
}

enum AndroidStreamIntent {
  automatic,
  onDemand,
  live,
}

enum AndroidMediaFormat {
  automatic,
  hls,
  mp4,
  mov,
  matroska,
  webm,
  mpegTs,
  mpegPs,
  flv,
  avi,
}

enum AndroidNetworkPolicyKind {
  platformDefault,
  managed,
}

enum AndroidBufferKind {
  automatic,
  lowLatency,
  smoothPlayback,
  bounded,
}

enum AndroidDecoderPolicy {
  systemDefault,
  hardwarePreferred,
  hardwareRequired,
}

enum AndroidAudioPolicy {
  appManaged,
  pluginManagedMediaPlayback,
}

enum AndroidAssessmentOutcome {
  compatible,
  incompatible,
  requiresInspection,
}

enum AndroidPlaybackStatus {
  idle,
  loading,
  ready,
  playing,
  paused,
  buffering,
  completed,
  failed,
}

enum AndroidEngine {
  unknown,
  media3,
}

enum AndroidTrackKind {
  audio,
  video,
}

enum AndroidPlayerOperation {
  seek,
  seekToLiveEdge,
  playbackSpeed,
  audioTrackSelection,
  videoConstraints,
  volume,
  stop,
}

enum AndroidDecoderMode {
  unknown,
  hardware,
  software,
}

enum AndroidDecoderEvidence {
  none,
  hardwareOnly,
  hardwareAndSoftware,
}

enum AndroidFailureCategory {
  cancelled,
  unsupported,
  source,
  network,
  container,
  decoder,
  render,
  resource,
  protocol,
  platform,
  internal,
}

enum AndroidFailureScope {
  command,
  session,
  player,
}

class AndroidPlayerOptionsMessage {
  AndroidPlayerOptionsMessage({
    required this.decoderPolicy,
    required this.audioPolicy,
    required this.positionUpdateIntervalMs,
  });

  AndroidDecoderPolicy decoderPolicy;

  AndroidAudioPolicy audioPolicy;

  int positionUpdateIntervalMs;

  List<Object?> _toList() {
    return <Object?>[
      decoderPolicy,
      audioPolicy,
      positionUpdateIntervalMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidPlayerOptionsMessage decode(Object result) {
    result as List<Object?>;
    return AndroidPlayerOptionsMessage(
      decoderPolicy: result[0]! as AndroidDecoderPolicy,
      audioPolicy: result[1]! as AndroidAudioPolicy,
      positionUpdateIntervalMs: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidPlayerOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(decoderPolicy, other.decoderPolicy) && _deepEquals(audioPolicy, other.audioPolicy) && _deepEquals(positionUpdateIntervalMs, other.positionUpdateIntervalMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidPlayerOptionsMessage(decoderPolicy: $decoderPolicy, audioPolicy: $audioPolicy, positionUpdateIntervalMs: $positionUpdateIntervalMs)';
  }
}

class AndroidCreateRequest {
  AndroidCreateRequest({
    required this.schemaMajor,
    required this.options,
  });

  int schemaMajor;

  AndroidPlayerOptionsMessage options;

  List<Object?> _toList() {
    return <Object?>[
      schemaMajor,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidCreateRequest decode(Object result) {
    result as List<Object?>;
    return AndroidCreateRequest(
      schemaMajor: result[0]! as int,
      options: result[1]! as AndroidPlayerOptionsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidCreateRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(schemaMajor, other.schemaMajor) && _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidCreateRequest(schemaMajor: $schemaMajor, options: $options)';
  }
}

class AndroidCreateReply {
  AndroidCreateReply({
    required this.schemaMajor,
    required this.spiMajor,
    required this.channelSuffix,
    required this.textureId,
    required this.implementationName,
    required this.implementationVersion,
    required this.capabilities,
    required this.initialState,
  });

  int schemaMajor;

  int spiMajor;

  String channelSuffix;

  int textureId;

  String implementationName;

  String implementationVersion;

  AndroidCapabilitiesMessage capabilities;

  AndroidStateMessage initialState;

  List<Object?> _toList() {
    return <Object?>[
      schemaMajor,
      spiMajor,
      channelSuffix,
      textureId,
      implementationName,
      implementationVersion,
      capabilities,
      initialState,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidCreateReply decode(Object result) {
    result as List<Object?>;
    return AndroidCreateReply(
      schemaMajor: result[0]! as int,
      spiMajor: result[1]! as int,
      channelSuffix: result[2]! as String,
      textureId: result[3]! as int,
      implementationName: result[4]! as String,
      implementationVersion: result[5]! as String,
      capabilities: result[6]! as AndroidCapabilitiesMessage,
      initialState: result[7]! as AndroidStateMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidCreateReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(schemaMajor, other.schemaMajor) && _deepEquals(spiMajor, other.spiMajor) && _deepEquals(channelSuffix, other.channelSuffix) && _deepEquals(textureId, other.textureId) && _deepEquals(implementationName, other.implementationName) && _deepEquals(implementationVersion, other.implementationVersion) && _deepEquals(capabilities, other.capabilities) && _deepEquals(initialState, other.initialState);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidCreateReply(schemaMajor: $schemaMajor, spiMajor: $spiMajor, channelSuffix: $channelSuffix, textureId: $textureId, implementationName: $implementationName, implementationVersion: $implementationVersion, capabilities: $capabilities, initialState: $initialState)';
  }
}

class AndroidCapabilitiesMessage {
  AndroidCapabilitiesMessage({
    required this.deviceProfile,
    required this.availableEngines,
    required this.decoderEvidence,
    this.maxConcurrentVideoDecoders,
    this.maxWidth,
    this.maxHeight,
    required this.hardwareVideoCodecs,
    required this.supportedOperations,
  });

  String deviceProfile;

  List<AndroidEngine> availableEngines;

  AndroidDecoderEvidence decoderEvidence;

  int? maxConcurrentVideoDecoders;

  int? maxWidth;

  int? maxHeight;

  List<String> hardwareVideoCodecs;

  List<AndroidPlayerOperation> supportedOperations;

  List<Object?> _toList() {
    return <Object?>[
      deviceProfile,
      availableEngines,
      decoderEvidence,
      maxConcurrentVideoDecoders,
      maxWidth,
      maxHeight,
      hardwareVideoCodecs,
      supportedOperations,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidCapabilitiesMessage decode(Object result) {
    result as List<Object?>;
    return AndroidCapabilitiesMessage(
      deviceProfile: result[0]! as String,
      availableEngines: (result[1]! as List<Object?>).cast<AndroidEngine>(),
      decoderEvidence: result[2]! as AndroidDecoderEvidence,
      maxConcurrentVideoDecoders: result[3] as int?,
      maxWidth: result[4] as int?,
      maxHeight: result[5] as int?,
      hardwareVideoCodecs: (result[6]! as List<Object?>).cast<String>(),
      supportedOperations: (result[7]! as List<Object?>).cast<AndroidPlayerOperation>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidCapabilitiesMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(deviceProfile, other.deviceProfile) && _deepEquals(availableEngines, other.availableEngines) && _deepEquals(decoderEvidence, other.decoderEvidence) && _deepEquals(maxConcurrentVideoDecoders, other.maxConcurrentVideoDecoders) && _deepEquals(maxWidth, other.maxWidth) && _deepEquals(maxHeight, other.maxHeight) && _deepEquals(hardwareVideoCodecs, other.hardwareVideoCodecs) && _deepEquals(supportedOperations, other.supportedOperations);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidCapabilitiesMessage(deviceProfile: $deviceProfile, availableEngines: $availableEngines, decoderEvidence: $decoderEvidence, maxConcurrentVideoDecoders: $maxConcurrentVideoDecoders, maxWidth: $maxWidth, maxHeight: $maxHeight, hardwareVideoCodecs: $hardwareVideoCodecs, supportedOperations: $supportedOperations)';
  }
}

class AndroidHttpRequestMessage {
  AndroidHttpRequestMessage({
    required this.headers,
    required this.credentials,
  });

  Map<String, String> headers;

  Map<String, String> credentials;

  List<Object?> _toList() {
    return <Object?>[
      headers,
      credentials,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidHttpRequestMessage decode(Object result) {
    result as List<Object?>;
    return AndroidHttpRequestMessage(
      headers: (result[0]! as Map<Object?, Object?>).cast<String, String>(),
      credentials: (result[1]! as Map<Object?, Object?>).cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidHttpRequestMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(headers, other.headers) && _deepEquals(credentials, other.credentials);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidHttpRequestMessage(headers: $headers, credentials: $credentials)';
  }
}

class AndroidNetworkPolicyMessage {
  AndroidNetworkPolicyMessage({
    required this.kind,
    this.connectTimeoutMs,
    this.readTimeoutMs,
    this.maxRetries,
    this.baseRetryDelayMs,
    this.maxRetryDelayMs,
    this.maxRedirects,
  });

  AndroidNetworkPolicyKind kind;

  int? connectTimeoutMs;

  int? readTimeoutMs;

  int? maxRetries;

  int? baseRetryDelayMs;

  int? maxRetryDelayMs;

  int? maxRedirects;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      connectTimeoutMs,
      readTimeoutMs,
      maxRetries,
      baseRetryDelayMs,
      maxRetryDelayMs,
      maxRedirects,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidNetworkPolicyMessage decode(Object result) {
    result as List<Object?>;
    return AndroidNetworkPolicyMessage(
      kind: result[0]! as AndroidNetworkPolicyKind,
      connectTimeoutMs: result[1] as int?,
      readTimeoutMs: result[2] as int?,
      maxRetries: result[3] as int?,
      baseRetryDelayMs: result[4] as int?,
      maxRetryDelayMs: result[5] as int?,
      maxRedirects: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidNetworkPolicyMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(connectTimeoutMs, other.connectTimeoutMs) && _deepEquals(readTimeoutMs, other.readTimeoutMs) && _deepEquals(maxRetries, other.maxRetries) && _deepEquals(baseRetryDelayMs, other.baseRetryDelayMs) && _deepEquals(maxRetryDelayMs, other.maxRetryDelayMs) && _deepEquals(maxRedirects, other.maxRedirects);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidNetworkPolicyMessage(kind: $kind, connectTimeoutMs: $connectTimeoutMs, readTimeoutMs: $readTimeoutMs, maxRetries: $maxRetries, baseRetryDelayMs: $baseRetryDelayMs, maxRetryDelayMs: $maxRetryDelayMs, maxRedirects: $maxRedirects)';
  }
}

class AndroidSourceMessage {
  AndroidSourceMessage({
    required this.kind,
    required this.locator,
    required this.intent,
    required this.format,
    this.request,
    this.networkPolicy,
  });

  AndroidSourceKind kind;

  String locator;

  AndroidStreamIntent intent;

  AndroidMediaFormat format;

  AndroidHttpRequestMessage? request;

  AndroidNetworkPolicyMessage? networkPolicy;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      locator,
      intent,
      format,
      request,
      networkPolicy,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSourceMessage decode(Object result) {
    result as List<Object?>;
    return AndroidSourceMessage(
      kind: result[0]! as AndroidSourceKind,
      locator: result[1]! as String,
      intent: result[2]! as AndroidStreamIntent,
      format: result[3]! as AndroidMediaFormat,
      request: result[4] as AndroidHttpRequestMessage?,
      networkPolicy: result[5] as AndroidNetworkPolicyMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSourceMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(locator, other.locator) && _deepEquals(intent, other.intent) && _deepEquals(format, other.format) && _deepEquals(request, other.request) && _deepEquals(networkPolicy, other.networkPolicy);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSourceMessage(kind: $kind, locator: $locator, intent: $intent, format: $format, request: $request, networkPolicy: $networkPolicy)';
  }
}

class AndroidVideoConstraintsMessage {
  AndroidVideoConstraintsMessage({
    this.maxWidth,
    this.maxHeight,
    this.maxBitrate,
  });

  int? maxWidth;

  int? maxHeight;

  int? maxBitrate;

  List<Object?> _toList() {
    return <Object?>[
      maxWidth,
      maxHeight,
      maxBitrate,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidVideoConstraintsMessage decode(Object result) {
    result as List<Object?>;
    return AndroidVideoConstraintsMessage(
      maxWidth: result[0] as int?,
      maxHeight: result[1] as int?,
      maxBitrate: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidVideoConstraintsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(maxWidth, other.maxWidth) && _deepEquals(maxHeight, other.maxHeight) && _deepEquals(maxBitrate, other.maxBitrate);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidVideoConstraintsMessage(maxWidth: $maxWidth, maxHeight: $maxHeight, maxBitrate: $maxBitrate)';
  }
}

class AndroidBufferStrategyMessage {
  AndroidBufferStrategyMessage({
    required this.kind,
    this.minDurationMs,
    this.maxDurationMs,
    this.maxManagedBytes,
  });

  AndroidBufferKind kind;

  int? minDurationMs;

  int? maxDurationMs;

  int? maxManagedBytes;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      minDurationMs,
      maxDurationMs,
      maxManagedBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidBufferStrategyMessage decode(Object result) {
    result as List<Object?>;
    return AndroidBufferStrategyMessage(
      kind: result[0]! as AndroidBufferKind,
      minDurationMs: result[1] as int?,
      maxDurationMs: result[2] as int?,
      maxManagedBytes: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidBufferStrategyMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(minDurationMs, other.minDurationMs) && _deepEquals(maxDurationMs, other.maxDurationMs) && _deepEquals(maxManagedBytes, other.maxManagedBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidBufferStrategyMessage(kind: $kind, minDurationMs: $minDurationMs, maxDurationMs: $maxDurationMs, maxManagedBytes: $maxManagedBytes)';
  }
}

class AndroidLoadOptionsMessage {
  AndroidLoadOptionsMessage({
    required this.autoplay,
    this.startPositionMs,
    required this.bufferStrategy,
    required this.videoConstraints,
    this.decoderPolicyOverride,
  });

  bool autoplay;

  int? startPositionMs;

  AndroidBufferStrategyMessage bufferStrategy;

  AndroidVideoConstraintsMessage videoConstraints;

  AndroidDecoderPolicy? decoderPolicyOverride;

  List<Object?> _toList() {
    return <Object?>[
      autoplay,
      startPositionMs,
      bufferStrategy,
      videoConstraints,
      decoderPolicyOverride,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidLoadOptionsMessage decode(Object result) {
    result as List<Object?>;
    return AndroidLoadOptionsMessage(
      autoplay: result[0]! as bool,
      startPositionMs: result[1] as int?,
      bufferStrategy: result[2]! as AndroidBufferStrategyMessage,
      videoConstraints: result[3]! as AndroidVideoConstraintsMessage,
      decoderPolicyOverride: result[4] as AndroidDecoderPolicy?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidLoadOptionsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(autoplay, other.autoplay) && _deepEquals(startPositionMs, other.startPositionMs) && _deepEquals(bufferStrategy, other.bufferStrategy) && _deepEquals(videoConstraints, other.videoConstraints) && _deepEquals(decoderPolicyOverride, other.decoderPolicyOverride);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidLoadOptionsMessage(autoplay: $autoplay, startPositionMs: $startPositionMs, bufferStrategy: $bufferStrategy, videoConstraints: $videoConstraints, decoderPolicyOverride: $decoderPolicyOverride)';
  }
}

class AndroidAssessRequest {
  AndroidAssessRequest({
    required this.source,
    required this.options,
  });

  AndroidSourceMessage source;

  AndroidLoadOptionsMessage options;

  List<Object?> _toList() {
    return <Object?>[
      source,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAssessRequest decode(Object result) {
    result as List<Object?>;
    return AndroidAssessRequest(
      source: result[0]! as AndroidSourceMessage,
      options: result[1]! as AndroidLoadOptionsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAssessRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(source, other.source) && _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAssessRequest(source: $source, options: $options)';
  }
}

class AndroidLoadRequest {
  AndroidLoadRequest({
    required this.source,
    required this.options,
  });

  AndroidSourceMessage source;

  AndroidLoadOptionsMessage options;

  List<Object?> _toList() {
    return <Object?>[
      source,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidLoadRequest decode(Object result) {
    result as List<Object?>;
    return AndroidLoadRequest(
      source: result[0]! as AndroidSourceMessage,
      options: result[1]! as AndroidLoadOptionsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidLoadRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(source, other.source) && _deepEquals(options, other.options);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidLoadRequest(source: $source, options: $options)';
  }
}

class AndroidAssessmentReply {
  AndroidAssessmentReply({
    required this.outcome,
    this.candidateEngine,
    required this.satisfiedRequirements,
    required this.limitations,
    this.rejection,
  });

  AndroidAssessmentOutcome outcome;

  AndroidEngine? candidateEngine;

  List<String> satisfiedRequirements;

  List<String> limitations;

  AndroidFailureMessage? rejection;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
      candidateEngine,
      satisfiedRequirements,
      limitations,
      rejection,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidAssessmentReply decode(Object result) {
    result as List<Object?>;
    return AndroidAssessmentReply(
      outcome: result[0]! as AndroidAssessmentOutcome,
      candidateEngine: result[1] as AndroidEngine?,
      satisfiedRequirements: (result[2]! as List<Object?>).cast<String>(),
      limitations: (result[3]! as List<Object?>).cast<String>(),
      rejection: result[4] as AndroidFailureMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidAssessmentReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) && _deepEquals(candidateEngine, other.candidateEngine) && _deepEquals(satisfiedRequirements, other.satisfiedRequirements) && _deepEquals(limitations, other.limitations) && _deepEquals(rejection, other.rejection);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidAssessmentReply(outcome: $outcome, candidateEngine: $candidateEngine, satisfiedRequirements: $satisfiedRequirements, limitations: $limitations, rejection: $rejection)';
  }
}

class AndroidLoadReply {
  AndroidLoadReply({
    required this.sessionId,
  });

  String sessionId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidLoadReply decode(Object result) {
    result as List<Object?>;
    return AndroidLoadReply(
      sessionId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidLoadReply || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidLoadReply(sessionId: $sessionId)';
  }
}

class AndroidSessionCommand {
  AndroidSessionCommand({
    required this.sessionId,
  });

  String sessionId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSessionCommand decode(Object result) {
    result as List<Object?>;
    return AndroidSessionCommand(
      sessionId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSessionCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSessionCommand(sessionId: $sessionId)';
  }
}

class AndroidSeekCommand {
  AndroidSeekCommand({
    required this.sessionId,
    required this.positionMs,
  });

  String sessionId;

  int positionMs;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      positionMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSeekCommand decode(Object result) {
    result as List<Object?>;
    return AndroidSeekCommand(
      sessionId: result[0]! as String,
      positionMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSeekCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(positionMs, other.positionMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSeekCommand(sessionId: $sessionId, positionMs: $positionMs)';
  }
}

class AndroidSpeedCommand {
  AndroidSpeedCommand({
    required this.sessionId,
    required this.speed,
  });

  String sessionId;

  double speed;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      speed,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSpeedCommand decode(Object result) {
    result as List<Object?>;
    return AndroidSpeedCommand(
      sessionId: result[0]! as String,
      speed: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSpeedCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(speed, other.speed);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSpeedCommand(sessionId: $sessionId, speed: $speed)';
  }
}

class AndroidTrackCommand {
  AndroidTrackCommand({
    required this.sessionId,
    required this.trackId,
  });

  String sessionId;

  String trackId;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      trackId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidTrackCommand decode(Object result) {
    result as List<Object?>;
    return AndroidTrackCommand(
      sessionId: result[0]! as String,
      trackId: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidTrackCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(trackId, other.trackId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidTrackCommand(sessionId: $sessionId, trackId: $trackId)';
  }
}

class AndroidVideoConstraintsCommand {
  AndroidVideoConstraintsCommand({
    required this.sessionId,
    required this.constraints,
  });

  String sessionId;

  AndroidVideoConstraintsMessage constraints;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      constraints,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidVideoConstraintsCommand decode(Object result) {
    result as List<Object?>;
    return AndroidVideoConstraintsCommand(
      sessionId: result[0]! as String,
      constraints: result[1]! as AndroidVideoConstraintsMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidVideoConstraintsCommand || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(constraints, other.constraints);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidVideoConstraintsCommand(sessionId: $sessionId, constraints: $constraints)';
  }
}

class AndroidDvrWindowMessage {
  AndroidDvrWindowMessage({
    required this.startMs,
    required this.endMs,
  });

  int startMs;

  int endMs;

  List<Object?> _toList() {
    return <Object?>[
      startMs,
      endMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidDvrWindowMessage decode(Object result) {
    result as List<Object?>;
    return AndroidDvrWindowMessage(
      startMs: result[0]! as int,
      endMs: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidDvrWindowMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(startMs, other.startMs) && _deepEquals(endMs, other.endMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidDvrWindowMessage(startMs: $startMs, endMs: $endMs)';
  }
}

class AndroidTimelineMessage {
  AndroidTimelineMessage({
    required this.positionMs,
    this.durationMs,
    required this.bufferedPositionMs,
    required this.isSeekable,
    required this.isLive,
    this.isAtLiveEdge,
    this.liveOffsetMs,
    this.dvrWindow,
  });

  int positionMs;

  int? durationMs;

  int bufferedPositionMs;

  bool isSeekable;

  bool isLive;

  bool? isAtLiveEdge;

  int? liveOffsetMs;

  AndroidDvrWindowMessage? dvrWindow;

  List<Object?> _toList() {
    return <Object?>[
      positionMs,
      durationMs,
      bufferedPositionMs,
      isSeekable,
      isLive,
      isAtLiveEdge,
      liveOffsetMs,
      dvrWindow,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidTimelineMessage decode(Object result) {
    result as List<Object?>;
    return AndroidTimelineMessage(
      positionMs: result[0]! as int,
      durationMs: result[1] as int?,
      bufferedPositionMs: result[2]! as int,
      isSeekable: result[3]! as bool,
      isLive: result[4]! as bool,
      isAtLiveEdge: result[5] as bool?,
      liveOffsetMs: result[6] as int?,
      dvrWindow: result[7] as AndroidDvrWindowMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidTimelineMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(positionMs, other.positionMs) && _deepEquals(durationMs, other.durationMs) && _deepEquals(bufferedPositionMs, other.bufferedPositionMs) && _deepEquals(isSeekable, other.isSeekable) && _deepEquals(isLive, other.isLive) && _deepEquals(isAtLiveEdge, other.isAtLiveEdge) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(dvrWindow, other.dvrWindow);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidTimelineMessage(positionMs: $positionMs, durationMs: $durationMs, bufferedPositionMs: $bufferedPositionMs, isSeekable: $isSeekable, isLive: $isLive, isAtLiveEdge: $isAtLiveEdge, liveOffsetMs: $liveOffsetMs, dvrWindow: $dvrWindow)';
  }
}

class AndroidSizeMessage {
  AndroidSizeMessage({
    required this.width,
    required this.height,
  });

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidSizeMessage decode(Object result) {
    result as List<Object?>;
    return AndroidSizeMessage(
      width: result[0]! as double,
      height: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidSizeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidSizeMessage(width: $width, height: $height)';
  }
}

class AndroidVideoGeometryMessage {
  AndroidVideoGeometryMessage({
    required this.encodedSize,
    required this.displaySize,
    required this.pixelAspectRatio,
    required this.rotationDegrees,
  });

  AndroidSizeMessage encodedSize;

  AndroidSizeMessage displaySize;

  double pixelAspectRatio;

  int rotationDegrees;

  List<Object?> _toList() {
    return <Object?>[
      encodedSize,
      displaySize,
      pixelAspectRatio,
      rotationDegrees,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidVideoGeometryMessage decode(Object result) {
    result as List<Object?>;
    return AndroidVideoGeometryMessage(
      encodedSize: result[0]! as AndroidSizeMessage,
      displaySize: result[1]! as AndroidSizeMessage,
      pixelAspectRatio: result[2]! as double,
      rotationDegrees: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidVideoGeometryMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encodedSize, other.encodedSize) && _deepEquals(displaySize, other.displaySize) && _deepEquals(pixelAspectRatio, other.pixelAspectRatio) && _deepEquals(rotationDegrees, other.rotationDegrees);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidVideoGeometryMessage(encodedSize: $encodedSize, displaySize: $displaySize, pixelAspectRatio: $pixelAspectRatio, rotationDegrees: $rotationDegrees)';
  }
}

class AndroidTrackMessage {
  AndroidTrackMessage({
    required this.id,
    required this.kind,
    this.label,
    this.language,
    this.codec,
    this.bitrate,
    this.width,
    this.height,
    required this.isSelected,
  });

  String id;

  AndroidTrackKind kind;

  String? label;

  String? language;

  String? codec;

  int? bitrate;

  int? width;

  int? height;

  bool isSelected;

  List<Object?> _toList() {
    return <Object?>[
      id,
      kind,
      label,
      language,
      codec,
      bitrate,
      width,
      height,
      isSelected,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidTrackMessage decode(Object result) {
    result as List<Object?>;
    return AndroidTrackMessage(
      id: result[0]! as String,
      kind: result[1]! as AndroidTrackKind,
      label: result[2] as String?,
      language: result[3] as String?,
      codec: result[4] as String?,
      bitrate: result[5] as int?,
      width: result[6] as int?,
      height: result[7] as int?,
      isSelected: result[8]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidTrackMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(kind, other.kind) && _deepEquals(label, other.label) && _deepEquals(language, other.language) && _deepEquals(codec, other.codec) && _deepEquals(bitrate, other.bitrate) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(isSelected, other.isSelected);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidTrackMessage(id: $id, kind: $kind, label: $label, language: $language, codec: $codec, bitrate: $bitrate, width: $width, height: $height, isSelected: $isSelected)';
  }
}

class AndroidMetricsMessage {
  AndroidMetricsMessage({
    this.loadToReadyMs,
    this.loadToFirstFrameMs,
    this.rebufferCount,
    this.rebufferDurationMs,
    this.droppedVideoFrames,
    this.audioUnderruns,
    this.estimatedBitrate,
    this.managedBufferedDurationMs,
    this.managedBufferedBytes,
    this.liveOffsetMs,
    this.reconnectCount,
  });

  int? loadToReadyMs;

  int? loadToFirstFrameMs;

  int? rebufferCount;

  int? rebufferDurationMs;

  int? droppedVideoFrames;

  int? audioUnderruns;

  int? estimatedBitrate;

  int? managedBufferedDurationMs;

  int? managedBufferedBytes;

  int? liveOffsetMs;

  int? reconnectCount;

  List<Object?> _toList() {
    return <Object?>[
      loadToReadyMs,
      loadToFirstFrameMs,
      rebufferCount,
      rebufferDurationMs,
      droppedVideoFrames,
      audioUnderruns,
      estimatedBitrate,
      managedBufferedDurationMs,
      managedBufferedBytes,
      liveOffsetMs,
      reconnectCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidMetricsMessage decode(Object result) {
    result as List<Object?>;
    return AndroidMetricsMessage(
      loadToReadyMs: result[0] as int?,
      loadToFirstFrameMs: result[1] as int?,
      rebufferCount: result[2] as int?,
      rebufferDurationMs: result[3] as int?,
      droppedVideoFrames: result[4] as int?,
      audioUnderruns: result[5] as int?,
      estimatedBitrate: result[6] as int?,
      managedBufferedDurationMs: result[7] as int?,
      managedBufferedBytes: result[8] as int?,
      liveOffsetMs: result[9] as int?,
      reconnectCount: result[10] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidMetricsMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(loadToReadyMs, other.loadToReadyMs) && _deepEquals(loadToFirstFrameMs, other.loadToFirstFrameMs) && _deepEquals(rebufferCount, other.rebufferCount) && _deepEquals(rebufferDurationMs, other.rebufferDurationMs) && _deepEquals(droppedVideoFrames, other.droppedVideoFrames) && _deepEquals(audioUnderruns, other.audioUnderruns) && _deepEquals(estimatedBitrate, other.estimatedBitrate) && _deepEquals(managedBufferedDurationMs, other.managedBufferedDurationMs) && _deepEquals(managedBufferedBytes, other.managedBufferedBytes) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(reconnectCount, other.reconnectCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidMetricsMessage(loadToReadyMs: $loadToReadyMs, loadToFirstFrameMs: $loadToFirstFrameMs, rebufferCount: $rebufferCount, rebufferDurationMs: $rebufferDurationMs, droppedVideoFrames: $droppedVideoFrames, audioUnderruns: $audioUnderruns, estimatedBitrate: $estimatedBitrate, managedBufferedDurationMs: $managedBufferedDurationMs, managedBufferedBytes: $managedBufferedBytes, liveOffsetMs: $liveOffsetMs, reconnectCount: $reconnectCount)';
  }
}

class AndroidFailureMessage {
  AndroidFailureMessage({
    required this.category,
    required this.code,
    required this.message,
    required this.retryable,
    required this.scope,
    required this.diagnosticId,
  });

  AndroidFailureCategory category;

  String code;

  String message;

  bool retryable;

  AndroidFailureScope scope;

  String diagnosticId;

  List<Object?> _toList() {
    return <Object?>[
      category,
      code,
      message,
      retryable,
      scope,
      diagnosticId,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidFailureMessage decode(Object result) {
    result as List<Object?>;
    return AndroidFailureMessage(
      category: result[0]! as AndroidFailureCategory,
      code: result[1]! as String,
      message: result[2]! as String,
      retryable: result[3]! as bool,
      scope: result[4]! as AndroidFailureScope,
      diagnosticId: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidFailureMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(category, other.category) && _deepEquals(code, other.code) && _deepEquals(message, other.message) && _deepEquals(retryable, other.retryable) && _deepEquals(scope, other.scope) && _deepEquals(diagnosticId, other.diagnosticId);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidFailureMessage(category: $category, code: $code, message: $message, retryable: $retryable, scope: $scope, diagnosticId: $diagnosticId)';
  }
}

class AndroidStateMessage {
  AndroidStateMessage({
    this.sessionId,
    required this.revision,
    required this.sequence,
    required this.status,
    required this.timeline,
    this.geometry,
    required this.audioTracks,
    required this.videoTracks,
    required this.engine,
    required this.decoderMode,
    this.decoderIdentity,
    required this.metrics,
    this.failure,
  });

  String? sessionId;

  int revision;

  int sequence;

  AndroidPlaybackStatus status;

  AndroidTimelineMessage timeline;

  AndroidVideoGeometryMessage? geometry;

  List<AndroidTrackMessage> audioTracks;

  List<AndroidTrackMessage> videoTracks;

  AndroidEngine engine;

  AndroidDecoderMode decoderMode;

  String? decoderIdentity;

  AndroidMetricsMessage metrics;

  AndroidFailureMessage? failure;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      status,
      timeline,
      geometry,
      audioTracks,
      videoTracks,
      engine,
      decoderMode,
      decoderIdentity,
      metrics,
      failure,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidStateMessage decode(Object result) {
    result as List<Object?>;
    return AndroidStateMessage(
      sessionId: result[0] as String?,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      status: result[3]! as AndroidPlaybackStatus,
      timeline: result[4]! as AndroidTimelineMessage,
      geometry: result[5] as AndroidVideoGeometryMessage?,
      audioTracks: (result[6]! as List<Object?>).cast<AndroidTrackMessage>(),
      videoTracks: (result[7]! as List<Object?>).cast<AndroidTrackMessage>(),
      engine: result[8]! as AndroidEngine,
      decoderMode: result[9]! as AndroidDecoderMode,
      decoderIdentity: result[10] as String?,
      metrics: result[11]! as AndroidMetricsMessage,
      failure: result[12] as AndroidFailureMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidStateMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(status, other.status) && _deepEquals(timeline, other.timeline) && _deepEquals(geometry, other.geometry) && _deepEquals(audioTracks, other.audioTracks) && _deepEquals(videoTracks, other.videoTracks) && _deepEquals(engine, other.engine) && _deepEquals(decoderMode, other.decoderMode) && _deepEquals(decoderIdentity, other.decoderIdentity) && _deepEquals(metrics, other.metrics) && _deepEquals(failure, other.failure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidStateMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, status: $status, timeline: $timeline, geometry: $geometry, audioTracks: $audioTracks, videoTracks: $videoTracks, engine: $engine, decoderMode: $decoderMode, decoderIdentity: $decoderIdentity, metrics: $metrics, failure: $failure)';
  }
}

class AndroidStateDeltaMessage {
  AndroidStateDeltaMessage({
    required this.sessionId,
    required this.previousRevision,
    required this.revision,
    required this.sequence,
    this.positionMs,
    this.bufferedPositionMs,
    required this.hasIsAtLiveEdge,
    this.isAtLiveEdge,
    required this.hasLiveOffsetMs,
    this.liveOffsetMs,
    this.metrics,
  });

  String sessionId;

  int previousRevision;

  int revision;

  int sequence;

  int? positionMs;

  int? bufferedPositionMs;

  bool hasIsAtLiveEdge;

  bool? isAtLiveEdge;

  bool hasLiveOffsetMs;

  int? liveOffsetMs;

  AndroidMetricsDeltaMessage? metrics;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      previousRevision,
      revision,
      sequence,
      positionMs,
      bufferedPositionMs,
      hasIsAtLiveEdge,
      isAtLiveEdge,
      hasLiveOffsetMs,
      liveOffsetMs,
      metrics,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidStateDeltaMessage decode(Object result) {
    result as List<Object?>;
    return AndroidStateDeltaMessage(
      sessionId: result[0]! as String,
      previousRevision: result[1]! as int,
      revision: result[2]! as int,
      sequence: result[3]! as int,
      positionMs: result[4] as int?,
      bufferedPositionMs: result[5] as int?,
      hasIsAtLiveEdge: result[6]! as bool,
      isAtLiveEdge: result[7] as bool?,
      hasLiveOffsetMs: result[8]! as bool,
      liveOffsetMs: result[9] as int?,
      metrics: result[10] as AndroidMetricsDeltaMessage?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidStateDeltaMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(previousRevision, other.previousRevision) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(positionMs, other.positionMs) && _deepEquals(bufferedPositionMs, other.bufferedPositionMs) && _deepEquals(hasIsAtLiveEdge, other.hasIsAtLiveEdge) && _deepEquals(isAtLiveEdge, other.isAtLiveEdge) && _deepEquals(hasLiveOffsetMs, other.hasLiveOffsetMs) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(metrics, other.metrics);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidStateDeltaMessage(sessionId: $sessionId, previousRevision: $previousRevision, revision: $revision, sequence: $sequence, positionMs: $positionMs, bufferedPositionMs: $bufferedPositionMs, hasIsAtLiveEdge: $hasIsAtLiveEdge, isAtLiveEdge: $isAtLiveEdge, hasLiveOffsetMs: $hasLiveOffsetMs, liveOffsetMs: $liveOffsetMs, metrics: $metrics)';
  }
}

class AndroidMetricsDeltaMessage {
  AndroidMetricsDeltaMessage({
    required this.hasLoadToReadyMs,
    this.loadToReadyMs,
    required this.hasLoadToFirstFrameMs,
    this.loadToFirstFrameMs,
    required this.hasRebufferCount,
    this.rebufferCount,
    required this.hasRebufferDurationMs,
    this.rebufferDurationMs,
    required this.hasDroppedVideoFrames,
    this.droppedVideoFrames,
    required this.hasAudioUnderruns,
    this.audioUnderruns,
    required this.hasEstimatedBitrate,
    this.estimatedBitrate,
    required this.hasManagedBufferedDurationMs,
    this.managedBufferedDurationMs,
    required this.hasManagedBufferedBytes,
    this.managedBufferedBytes,
    required this.hasLiveOffsetMs,
    this.liveOffsetMs,
    required this.hasReconnectCount,
    this.reconnectCount,
  });

  bool hasLoadToReadyMs;

  int? loadToReadyMs;

  bool hasLoadToFirstFrameMs;

  int? loadToFirstFrameMs;

  bool hasRebufferCount;

  int? rebufferCount;

  bool hasRebufferDurationMs;

  int? rebufferDurationMs;

  bool hasDroppedVideoFrames;

  int? droppedVideoFrames;

  bool hasAudioUnderruns;

  int? audioUnderruns;

  bool hasEstimatedBitrate;

  int? estimatedBitrate;

  bool hasManagedBufferedDurationMs;

  int? managedBufferedDurationMs;

  bool hasManagedBufferedBytes;

  int? managedBufferedBytes;

  bool hasLiveOffsetMs;

  int? liveOffsetMs;

  bool hasReconnectCount;

  int? reconnectCount;

  List<Object?> _toList() {
    return <Object?>[
      hasLoadToReadyMs,
      loadToReadyMs,
      hasLoadToFirstFrameMs,
      loadToFirstFrameMs,
      hasRebufferCount,
      rebufferCount,
      hasRebufferDurationMs,
      rebufferDurationMs,
      hasDroppedVideoFrames,
      droppedVideoFrames,
      hasAudioUnderruns,
      audioUnderruns,
      hasEstimatedBitrate,
      estimatedBitrate,
      hasManagedBufferedDurationMs,
      managedBufferedDurationMs,
      hasManagedBufferedBytes,
      managedBufferedBytes,
      hasLiveOffsetMs,
      liveOffsetMs,
      hasReconnectCount,
      reconnectCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidMetricsDeltaMessage decode(Object result) {
    result as List<Object?>;
    return AndroidMetricsDeltaMessage(
      hasLoadToReadyMs: result[0]! as bool,
      loadToReadyMs: result[1] as int?,
      hasLoadToFirstFrameMs: result[2]! as bool,
      loadToFirstFrameMs: result[3] as int?,
      hasRebufferCount: result[4]! as bool,
      rebufferCount: result[5] as int?,
      hasRebufferDurationMs: result[6]! as bool,
      rebufferDurationMs: result[7] as int?,
      hasDroppedVideoFrames: result[8]! as bool,
      droppedVideoFrames: result[9] as int?,
      hasAudioUnderruns: result[10]! as bool,
      audioUnderruns: result[11] as int?,
      hasEstimatedBitrate: result[12]! as bool,
      estimatedBitrate: result[13] as int?,
      hasManagedBufferedDurationMs: result[14]! as bool,
      managedBufferedDurationMs: result[15] as int?,
      hasManagedBufferedBytes: result[16]! as bool,
      managedBufferedBytes: result[17] as int?,
      hasLiveOffsetMs: result[18]! as bool,
      liveOffsetMs: result[19] as int?,
      hasReconnectCount: result[20]! as bool,
      reconnectCount: result[21] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidMetricsDeltaMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(hasLoadToReadyMs, other.hasLoadToReadyMs) && _deepEquals(loadToReadyMs, other.loadToReadyMs) && _deepEquals(hasLoadToFirstFrameMs, other.hasLoadToFirstFrameMs) && _deepEquals(loadToFirstFrameMs, other.loadToFirstFrameMs) && _deepEquals(hasRebufferCount, other.hasRebufferCount) && _deepEquals(rebufferCount, other.rebufferCount) && _deepEquals(hasRebufferDurationMs, other.hasRebufferDurationMs) && _deepEquals(rebufferDurationMs, other.rebufferDurationMs) && _deepEquals(hasDroppedVideoFrames, other.hasDroppedVideoFrames) && _deepEquals(droppedVideoFrames, other.droppedVideoFrames) && _deepEquals(hasAudioUnderruns, other.hasAudioUnderruns) && _deepEquals(audioUnderruns, other.audioUnderruns) && _deepEquals(hasEstimatedBitrate, other.hasEstimatedBitrate) && _deepEquals(estimatedBitrate, other.estimatedBitrate) && _deepEquals(hasManagedBufferedDurationMs, other.hasManagedBufferedDurationMs) && _deepEquals(managedBufferedDurationMs, other.managedBufferedDurationMs) && _deepEquals(hasManagedBufferedBytes, other.hasManagedBufferedBytes) && _deepEquals(managedBufferedBytes, other.managedBufferedBytes) && _deepEquals(hasLiveOffsetMs, other.hasLiveOffsetMs) && _deepEquals(liveOffsetMs, other.liveOffsetMs) && _deepEquals(hasReconnectCount, other.hasReconnectCount) && _deepEquals(reconnectCount, other.reconnectCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidMetricsDeltaMessage(hasLoadToReadyMs: $hasLoadToReadyMs, loadToReadyMs: $loadToReadyMs, hasLoadToFirstFrameMs: $hasLoadToFirstFrameMs, loadToFirstFrameMs: $loadToFirstFrameMs, hasRebufferCount: $hasRebufferCount, rebufferCount: $rebufferCount, hasRebufferDurationMs: $hasRebufferDurationMs, rebufferDurationMs: $rebufferDurationMs, hasDroppedVideoFrames: $hasDroppedVideoFrames, droppedVideoFrames: $droppedVideoFrames, hasAudioUnderruns: $hasAudioUnderruns, audioUnderruns: $audioUnderruns, hasEstimatedBitrate: $hasEstimatedBitrate, estimatedBitrate: $estimatedBitrate, hasManagedBufferedDurationMs: $hasManagedBufferedDurationMs, managedBufferedDurationMs: $managedBufferedDurationMs, hasManagedBufferedBytes: $hasManagedBufferedBytes, managedBufferedBytes: $managedBufferedBytes, hasLiveOffsetMs: $hasLiveOffsetMs, liveOffsetMs: $liveOffsetMs, hasReconnectCount: $hasReconnectCount, reconnectCount: $reconnectCount)';
  }
}

class AndroidFirstFrameMessage {
  AndroidFirstFrameMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidFirstFrameMessage decode(Object result) {
    result as List<Object?>;
    return AndroidFirstFrameMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidFirstFrameMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidFirstFrameMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs)';
  }
}

class AndroidRetryScheduledMessage {
  AndroidRetryScheduledMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
    required this.retryIndex,
    required this.delayMs,
    required this.failure,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  int retryIndex;

  int delayMs;

  AndroidFailureMessage failure;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
      retryIndex,
      delayMs,
      failure,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidRetryScheduledMessage decode(Object result) {
    result as List<Object?>;
    return AndroidRetryScheduledMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
      retryIndex: result[4]! as int,
      delayMs: result[5]! as int,
      failure: result[6]! as AndroidFailureMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidRetryScheduledMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs) && _deepEquals(retryIndex, other.retryIndex) && _deepEquals(delayMs, other.delayMs) && _deepEquals(failure, other.failure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidRetryScheduledMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs, retryIndex: $retryIndex, delayMs: $delayMs, failure: $failure)';
  }
}

class AndroidEngineChangedMessage {
  AndroidEngineChangedMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
    required this.previousEngine,
    required this.engine,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  AndroidEngine previousEngine;

  AndroidEngine engine;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
      previousEngine,
      engine,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidEngineChangedMessage decode(Object result) {
    result as List<Object?>;
    return AndroidEngineChangedMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
      previousEngine: result[4]! as AndroidEngine,
      engine: result[5]! as AndroidEngine,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidEngineChangedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs) && _deepEquals(previousEngine, other.previousEngine) && _deepEquals(engine, other.engine);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidEngineChangedMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs, previousEngine: $previousEngine, engine: $engine)';
  }
}

class AndroidPlaybackFailedMessage {
  AndroidPlaybackFailedMessage({
    required this.sessionId,
    required this.revision,
    required this.sequence,
    required this.occurredAtMs,
    required this.failure,
  });

  String sessionId;

  int revision;

  int sequence;

  int occurredAtMs;

  AndroidFailureMessage failure;

  List<Object?> _toList() {
    return <Object?>[
      sessionId,
      revision,
      sequence,
      occurredAtMs,
      failure,
    ];
  }

  Object encode() {
    return _toList();  }

  static AndroidPlaybackFailedMessage decode(Object result) {
    result as List<Object?>;
    return AndroidPlaybackFailedMessage(
      sessionId: result[0]! as String,
      revision: result[1]! as int,
      sequence: result[2]! as int,
      occurredAtMs: result[3]! as int,
      failure: result[4]! as AndroidFailureMessage,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AndroidPlaybackFailedMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sessionId, other.sessionId) && _deepEquals(revision, other.revision) && _deepEquals(sequence, other.sequence) && _deepEquals(occurredAtMs, other.occurredAtMs) && _deepEquals(failure, other.failure);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AndroidPlaybackFailedMessage(sessionId: $sessionId, revision: $revision, sequence: $sequence, occurredAtMs: $occurredAtMs, failure: $failure)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is AndroidSourceKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is AndroidStreamIntent) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AndroidMediaFormat) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is AndroidNetworkPolicyKind) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is AndroidBufferKind) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is AndroidDecoderPolicy) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is AndroidAudioPolicy) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is AndroidAssessmentOutcome) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is AndroidPlaybackStatus) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is AndroidEngine) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is AndroidTrackKind) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is AndroidPlayerOperation) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    }    else if (value is AndroidDecoderMode) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    }    else if (value is AndroidDecoderEvidence) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    }    else if (value is AndroidFailureCategory) {
      buffer.putUint8(143);
      writeValue(buffer, value.index);
    }    else if (value is AndroidFailureScope) {
      buffer.putUint8(144);
      writeValue(buffer, value.index);
    }    else if (value is AndroidPlayerOptionsMessage) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidCreateRequest) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidCreateReply) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidCapabilitiesMessage) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidHttpRequestMessage) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidNetworkPolicyMessage) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSourceMessage) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidVideoConstraintsMessage) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidBufferStrategyMessage) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidLoadOptionsMessage) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidAssessRequest) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidLoadRequest) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidAssessmentReply) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidLoadReply) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSessionCommand) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSeekCommand) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSpeedCommand) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidTrackCommand) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidVideoConstraintsCommand) {
      buffer.putUint8(163);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidDvrWindowMessage) {
      buffer.putUint8(164);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidTimelineMessage) {
      buffer.putUint8(165);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidSizeMessage) {
      buffer.putUint8(166);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidVideoGeometryMessage) {
      buffer.putUint8(167);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidTrackMessage) {
      buffer.putUint8(168);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidMetricsMessage) {
      buffer.putUint8(169);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidFailureMessage) {
      buffer.putUint8(170);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidStateMessage) {
      buffer.putUint8(171);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidStateDeltaMessage) {
      buffer.putUint8(172);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidMetricsDeltaMessage) {
      buffer.putUint8(173);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidFirstFrameMessage) {
      buffer.putUint8(174);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidRetryScheduledMessage) {
      buffer.putUint8(175);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidEngineChangedMessage) {
      buffer.putUint8(176);
      writeValue(buffer, value.encode());
    }    else if (value is AndroidPlaybackFailedMessage) {
      buffer.putUint8(177);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidSourceKind.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidStreamIntent.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidMediaFormat.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidNetworkPolicyKind.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidBufferKind.values[value];
      case 134:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidDecoderPolicy.values[value];
      case 135:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidAudioPolicy.values[value];
      case 136:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidAssessmentOutcome.values[value];
      case 137:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidPlaybackStatus.values[value];
      case 138:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidEngine.values[value];
      case 139:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidTrackKind.values[value];
      case 140:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidPlayerOperation.values[value];
      case 141:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidDecoderMode.values[value];
      case 142:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidDecoderEvidence.values[value];
      case 143:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidFailureCategory.values[value];
      case 144:
        final value = readValue(buffer) as int?;
        return value == null ? null : AndroidFailureScope.values[value];
      case 145:
        return AndroidPlayerOptionsMessage.decode(readValue(buffer)!);
      case 146:
        return AndroidCreateRequest.decode(readValue(buffer)!);
      case 147:
        return AndroidCreateReply.decode(readValue(buffer)!);
      case 148:
        return AndroidCapabilitiesMessage.decode(readValue(buffer)!);
      case 149:
        return AndroidHttpRequestMessage.decode(readValue(buffer)!);
      case 150:
        return AndroidNetworkPolicyMessage.decode(readValue(buffer)!);
      case 151:
        return AndroidSourceMessage.decode(readValue(buffer)!);
      case 152:
        return AndroidVideoConstraintsMessage.decode(readValue(buffer)!);
      case 153:
        return AndroidBufferStrategyMessage.decode(readValue(buffer)!);
      case 154:
        return AndroidLoadOptionsMessage.decode(readValue(buffer)!);
      case 155:
        return AndroidAssessRequest.decode(readValue(buffer)!);
      case 156:
        return AndroidLoadRequest.decode(readValue(buffer)!);
      case 157:
        return AndroidAssessmentReply.decode(readValue(buffer)!);
      case 158:
        return AndroidLoadReply.decode(readValue(buffer)!);
      case 159:
        return AndroidSessionCommand.decode(readValue(buffer)!);
      case 160:
        return AndroidSeekCommand.decode(readValue(buffer)!);
      case 161:
        return AndroidSpeedCommand.decode(readValue(buffer)!);
      case 162:
        return AndroidTrackCommand.decode(readValue(buffer)!);
      case 163:
        return AndroidVideoConstraintsCommand.decode(readValue(buffer)!);
      case 164:
        return AndroidDvrWindowMessage.decode(readValue(buffer)!);
      case 165:
        return AndroidTimelineMessage.decode(readValue(buffer)!);
      case 166:
        return AndroidSizeMessage.decode(readValue(buffer)!);
      case 167:
        return AndroidVideoGeometryMessage.decode(readValue(buffer)!);
      case 168:
        return AndroidTrackMessage.decode(readValue(buffer)!);
      case 169:
        return AndroidMetricsMessage.decode(readValue(buffer)!);
      case 170:
        return AndroidFailureMessage.decode(readValue(buffer)!);
      case 171:
        return AndroidStateMessage.decode(readValue(buffer)!);
      case 172:
        return AndroidStateDeltaMessage.decode(readValue(buffer)!);
      case 173:
        return AndroidMetricsDeltaMessage.decode(readValue(buffer)!);
      case 174:
        return AndroidFirstFrameMessage.decode(readValue(buffer)!);
      case 175:
        return AndroidRetryScheduledMessage.decode(readValue(buffer)!);
      case 176:
        return AndroidEngineChangedMessage.decode(readValue(buffer)!);
      case 177:
        return AndroidPlaybackFailedMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AndroidPlayerFactoryHostApi {
  /// Constructor for [AndroidPlayerFactoryHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AndroidPlayerFactoryHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AndroidCreateReply> create(AndroidCreateRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerFactoryHostApi.create$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidCreateReply;
  }
}

class AndroidPlayerHostApi {
  /// Constructor for [AndroidPlayerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AndroidPlayerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> attach() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.attach$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<AndroidAssessmentReply> assess(AndroidAssessRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.assess$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidAssessmentReply;
  }

  Future<AndroidLoadReply> load(AndroidLoadRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.load$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AndroidLoadReply;
  }

  Future<void> play(AndroidSessionCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.play$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> pause(AndroidSessionCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.pause$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekTo(AndroidSeekCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.seekTo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> seekToLiveEdge(AndroidSessionCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.seekToLiveEdge$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setPlaybackSpeed(AndroidSpeedCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.setPlaybackSpeed$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> selectAudioTrack(AndroidTrackCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.selectAudioTrack$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVideoConstraints(AndroidVideoConstraintsCommand command) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.setVideoConstraints$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[command]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setVolume(double volume) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.setVolume$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[volume]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> stop() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> dispose() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.yl_player_android.AndroidPlayerHostApi.dispose$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class AndroidPlayerFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onState(AndroidStateMessage state);

  void onStateDelta(AndroidStateDeltaMessage delta);

  void onFirstFrame(AndroidFirstFrameMessage event);

  void onRetryScheduled(AndroidRetryScheduledMessage event);

  void onEngineChanged(AndroidEngineChangedMessage event);

  void onPlaybackFailed(AndroidPlaybackFailedMessage event);

  static void setUp(AndroidPlayerFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_android.AndroidPlayerFlutterApi.onState$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AndroidStateMessage arg_state = args[0]! as AndroidStateMessage;
          try {
            api.onState(arg_state);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_android.AndroidPlayerFlutterApi.onStateDelta$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AndroidStateDeltaMessage arg_delta = args[0]! as AndroidStateDeltaMessage;
          try {
            api.onStateDelta(arg_delta);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_android.AndroidPlayerFlutterApi.onFirstFrame$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AndroidFirstFrameMessage arg_event = args[0]! as AndroidFirstFrameMessage;
          try {
            api.onFirstFrame(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_android.AndroidPlayerFlutterApi.onRetryScheduled$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AndroidRetryScheduledMessage arg_event = args[0]! as AndroidRetryScheduledMessage;
          try {
            api.onRetryScheduled(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_android.AndroidPlayerFlutterApi.onEngineChanged$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AndroidEngineChangedMessage arg_event = args[0]! as AndroidEngineChangedMessage;
          try {
            api.onEngineChanged(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.yl_player_android.AndroidPlayerFlutterApi.onPlaybackFailed$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final AndroidPlaybackFailedMessage arg_event = args[0]! as AndroidPlaybackFailedMessage;
          try {
            api.onPlaybackFailed(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
